import React, { createContext, useState, useContext } from 'react';

// 1. Define Base English Translations
const en = {
    detect: "Detect",
    dashboard: "Dashboard",
    history: "History",
    weather: "Weather",
    mandi: "Mandi Prices",
    schemes: "Gov Schemes",
    community: "Community",
    login: "Agent Portal",
    logout: "Sign Out",
    welcome: "Expert Care for Your Crops",
    homeSubtitle: "Identify diseases, get treatment plans, and consult with experts in seconds.",
    startDiagnosis: "Start Diagnosis",
    viewWeather: "View Weather",
    trustedBy: "Trusted by 20,000+ Farmers",
    accuracy: "98% Accuracy",
    instantReport: "Instant Report",
    expertHelp: "Expert Help",
    aiCropDoctor: "AI Crop Doctor",
    detectionSubtitle: "Capture or upload a leaf photo. Our AI identifies pathologies.",
    readyToScan: "Ready to Scan?",
    dropImage: "Drop image or click to browse",
    analyzeInfection: "Analyze Infection",
    computing: "Computing Pathologies...",
    recommendedRecovery: "Recommended Recovery",
    biologicalMeasures: "Biological Measures",
    saveToCloud: "Commit Report to Cloud",
    today: 'Today',
    delete: 'Delete',
    state: 'State',
    confirmDelete: 'Are you sure you want to delete this post?',
    mandiTitle: "Live Mandi Prices",
    mandiSubtitle: "Track real-time market rates for your crops across India.",
    cropName: "Crop Name",
    market: "Market",
    price: "Price (₹/Quintal)",
    trend: "Trend",
    schemesTitle: "Government Schemes",
    schemesSubtitle: "Financial aid and subsidies available for farmers.",
    applyNow: "Apply Now",
    details: "View Details",
    close: "Close",
    aboutScheme: "About Scheme",
    reqDocs: "Required Documents",
    communityTitle: "Farmer Community",
    communitySubtitle: "Discuss, share, and learn from fellow farmers.",
    newPost: "Start Discussion",
    replies: "Replies",
    welcomeBack: "Welcome Back",
    createAccount: "Create Account",
    secureLogin: "Access secure agricultural analytics",
    googleLogin: "Continue with Google",
    useEmail: "Or use email",
    email: "Email",
    password: "Password",
    signIn: "Sign In",
    joinNow: "Join Now",
    needAccount: "Need an account? New Registry",
    existingMember: "Existing Member? Secure Login",
    goodMorning: "Good Morning",
    goodAfternoon: "Good Afternoon",
    goodEvening: "Good Evening",
    dashboardSubtitle: "Here's what's happening with your crops today.",
    overallHealth: "Overall Crop Health",
    activeAlerts: "Active Alerts",
    tasksCompleted: "Tasks Completed",
    performanceIndex: "Performance Index",
    localWeather: "Local Weather",
    detailedForecast: "View Detailed Forecast",
    detectionHistory: "Detection History",
    liveMarket: "Live Market Rates",
    updated: "Updated",
    selectState: "Select State",
    searchMandi: "Search Market/Crop...",
    forecast: "Market Forecast",
    advice: "AI Suggestion",
    sellNow: "SELL NOW",
    hold: "HOLD STOCK",
    trendRising: "Prices likely to rise ↑",
    trendFalling: "Prices may fall ↓",
    trendStable: "Market stable",
    reasonRising: "High demand expected next week",
    reasonFalling: "Supply surplus expected",
    reasonStable: "No fluctuations observed",
    minPrice: "Min Price",
    maxPrice: "Max Price",
    modalPrice: "Modal Price",
    searchCity: "Search City...",
    humidity: "Humidity",
    windSpeed: "Wind Speed",
    precipitation: "Precipitation",
    filterPlaceholder: "Search crop or disease...",
    all: "All",
    healthy: "Healthy",
    issues: "Issues Detected",
    highSeverity: "High Severity",
    loadingDiscussions: "Loading Discussions...",
    noDiscussions: "No active discussions yet.",
    loadingRecords: "Fetching Records...",
    noRecords: "No records found matching your filters",
    exportPDF: "Export PDF",
    confidence: "Confidence",
    cloudSynced: "Cloud Synced",
    unknown: "Unknown",
    applyWebsite: "Apply on Official Website",
    deleteSuccess: "Record deleted successfully!",
    deleteFail: "Failed to delete...",
    newDiscussion: "New Discussion",
    shareTip: "Share your farming query or tip...",
    cancel: "Cancel",
    post: "Post",
    regionalGroups: "Regional Groups",
    regionalSubtitle: "Connect with farmers in your local language",

    schemesData: [
        { title: 'PM-Kisan Samman Nidhi', provider: 'Central Govt', benefit: '₹6,000/year', eligibility: 'Small/Marginal Farmers', link: 'https://pmkisan.gov.in/', details: 'Income support of ₹6,000 per year in three equal installments to all land holding farmer families.', docs: ['Aadhaar Card', 'Land Ownership Records', 'Bank Account Details'] },
        { title: 'Soil Health Card Scheme', provider: 'Ministry of Agri', benefit: 'Soil Analysis', eligibility: 'All Landholders', link: 'https://soilhealth.dac.gov.in/', details: 'Provides information to farmers on nutrient status of their soil along with recommendation on appropriate dosage of nutrients.', docs: ['Soil Sample', 'Aadhaar Card', 'Mobile Number'] },
        { title: 'PM Fasal Bima Yojana', provider: 'Central Govt', benefit: 'Crop Insurance', eligibility: 'KCC Holders', link: 'https://pmfby.gov.in/', details: 'One Nation-One Scheme theme. It provides comprehensive insurance coverage against failure of the crop.', docs: ['Sowing Certificate', 'Land Records', 'ID Proof'] },
        { title: 'Kisan Credit Card (KCC)', provider: 'State Bank', benefit: 'Low-interest Loans', eligibility: 'Credit Worthy Farmers', link: 'https://www.myscheme.gov.in/schemes/kcc', details: 'Timely and adequate credit to farmers to meet their production credit requirements.', docs: ['Application Form', 'Land Documents', 'Passport Photo'] },
        { title: 'Kusum Yojana', provider: 'MNRE', benefit: 'Solar Pump Subsidies', eligibility: 'Individual Farmers', link: 'https://pmkusum.mnre.gov.in/', details: 'Installation of standalone solar agriculture pumps and solarisation of existing grid-connected agricultural pumps.', docs: ['Solar Pump Application', 'Identity Proof', 'Land Papers'] },
        { title: 'Agri-Infrastructure Fund', provider: 'Central Govt', benefit: 'Storage Subsidies', eligibility: 'Startups & Farmers', link: 'https://theagriculturefund.nic.in/', details: 'Financing facility for investment in projects for post-harvest management infrastructure.', docs: ['DPR (Detailed Project Report)', 'KYC Documents', 'Bank Loan Approval'] },
    ],
    // Dynamic Data Keys (Crops & States) - English (Base)
    "Paddy (Dhan)": "Paddy (Dhan)",
    "Wheat": "Wheat",
    "Cotton": "Cotton",
    "Maize": "Maize",
    "Tomato": "Tomato",
    "Onion": "Onion",
    "Potato": "Potato",
    "Chilli": "Chilli",
    "Turmeric": "Turmeric",
    "Groundnut": "Groundnut",
    "Soybean": "Soybean",
    "Mustard": "Mustard",
    "Andhra Pradesh": "Andhra Pradesh",
    "Telangana": "Telangana",
    "Karnataka": "Karnataka",
    "Maharashtra": "Maharashtra",
    "Punjab": "Punjab",
    "Uttar Pradesh": "Uttar Pradesh",
    "Madhya Pradesh": "Madhya Pradesh",
    "Tamil Nadu": "Tamil Nadu",
    "Gujarat": "Gujarat",
    "Haryana": "Haryana"
};

// 2. Hindi Overrides
const hi = {
    detect: "पहचानें",
    dashboard: "डैशबोर्ड",
    history: "इतिहास",
    weather: "मौसम",
    mandi: "मंडी भाव",
    schemes: "सरकारी योजनाएं",
    community: "समुदाय",
    login: "एजेंट पोर्टल",
    logout: "लॉग आउट",
    welcome: "आपकी फसलों के लिए विशेषज्ञ देखभाल",
    homeSubtitle: "रोगों की पहचान करें, उपचार योजनाएं प्राप्त करें और विशेषज्ञों से सलाह लें।",
    startDiagnosis: "जांच शुरू करें",
    viewWeather: "मौसम देखें",
    trustedBy: "20,000+ किसानों द्वारा विश्वसनीय",
    accuracy: "98% सटीकता",
    instantReport: "तत्काल रिपोर्ट",
    expertHelp: "विशेषज्ञ सहायता",
    aiCropDoctor: "AI फसल डॉक्टर",
    detectionSubtitle: "पत्ते की फोटो लें या अपलोड करें। हमारा AI रोगों की पहचान करता है।",
    readyToScan: "स्कैन के लिए तैयार?",
    dropImage: "छवि डालें या ब्राउज़ करने के लिए क्लिक करें",
    analyzeInfection: "संक्रमण का विश्लेषण करें",
    computing: "रोगों की गणना हो रही है...",
    recommendedRecovery: "अनुशंसित उपचार",
    biologicalMeasures: "जैविक उपाय",
    saveToCloud: "रिपोर्ट क्लाउड पर सहेजें",
    today: 'आज',
    delete: 'मिटाएं',
    state: 'राज्य',
    confirmDelete: 'क्या आप वाकई इस पोस्ट को हटाना चाहते हैं?',
    mandiTitle: "लाइव मंडी भाव",
    mandiSubtitle: "भारत भर में अपनी फसलों के लिए वास्तविक समय के बाजार भावों को ट्रैक करें।",
    cropName: "फसल का नाम",
    market: "बाजार",
    price: "भाव (₹/क्विंटल)",
    trend: "रुझान",
    schemesTitle: "सरकारी योजनाएं",
    schemesSubtitle: "किसानों के लिए उपलब्ध वित्तीय सहायता और सब्सिडी।",
    applyNow: "अभी आवेदन करें",
    details: "विवरण देखें",
    close: "बंद करें",
    aboutScheme: "योजना के बारे में",
    reqDocs: "आवश्यक दस्तावेज",
    communityTitle: "किसान समुदाय",
    communitySubtitle: "साथी किसानों के साथ चर्चा करें, साझा करें और सीखें।",
    newPost: "चर्चा शुरू करें",
    replies: "जवाब",
    welcomeBack: "वापसी पर स्वागत है",
    createAccount: "खाता बनाएं",
    secureLogin: "सुरक्षित कृषि विश्लेषण तक पहुंचें",
    googleLogin: "गूगल के साथ जारी रखें",
    useEmail: "या ईमेल का उपयोग करें",
    email: "ईमेल",
    password: "पास्वर्ड",
    signIn: "साइन इन करें",
    joinNow: "अभी जुड़ें",
    needAccount: "खाता चाहिए? नया पंजीकरण",
    existingMember: "पुरानी सदस्य? सुरक्षित लॉगिन",
    goodMorning: "सुप्रभात",
    goodAfternoon: "नमस्ते",
    goodEvening: "शुभ संध्या",
    dashboardSubtitle: "आज आपकी फसलों का हाल यहाँ है।",
    overallHealth: "कुल फसल स्वास्थ्य",
    activeAlerts: "सक्रिय अलर्ट",
    tasksCompleted: "पूरे किए गए कार्य",
    performanceIndex: "प्रदर्शन सूचंक",
    localWeather: "स्थानीय मौसम",
    detailedForecast: "विस्तृत पूर्वानुमान देखें",
    detectionHistory: "जांच इतिहास",
    liveMarket: "लाइव बाजार भाव",
    updated: "अपडेट किया गया",
    selectState: "राज्य चुनें",
    searchMandi: "बाजार/फसल खोजें...",
    minPrice: "न्यूनतम भाव",
    maxPrice: "अधिकतम भाव",
    modalPrice: "औसत भाव",
    searchCity: "शहर खोजें...",
    humidity: "नमी",
    windSpeed: "हवा की गति",
    precipitation: "वर्षा",
    filterPlaceholder: "फसल या बीमारी खोजें...",
    all: "सभी",
    healthy: "स्वस्थ",
    issues: "समस्याएं मिलीं",
    highSeverity: "गंभीर समस्या",
    attemptDelete: "हटाने का प्रयास:",
    deleteSuccess: "रिकॉर्ड सफलतापूर्वक हटा दिया गया!",
    deleteFail: "हटाने में विफल...",
    newDiscussion: "नई चर्चा",
    shareTip: "अपना कृषि प्रश्न या टिप साझा करें...",
    cancel: "रद्द करें",
    post: "पोस्ट करें",
    regionalGroups: "क्षेत्रीय समूह",
    regionalSubtitle: "अपनी स्थानीय भाषा में किसानों से जुड़ें",
    applyWebsite: "आधिकारिक वेबसाइट पर आवेदन करें",
    schemesData: [
        { title: 'पीएम-किसान सम्मान निधि', provider: 'केंद्र सरकार', benefit: '₹6,000/वर्ष', eligibility: 'छोटे/सीमांत किसान', link: 'https://pmkisan.gov.in/', details: 'सभी भूमि पट्टाधारक किसान परिवारों को ₹6,000 प्रति वर्ष का आय समर्थन।', docs: ['आधार कार्ड', 'भूमि स्वामित्व रिकॉर्ड', 'बैंक खाता विवरण'] },
        { title: 'मृदा स्वास्थ्य कार्ड योजना', provider: 'कृषि मंत्रालय', benefit: 'मृदा विश्लेषण', eligibility: 'सभी पट्टाधारक', link: 'https://soilhealth.dac.gov.in/', details: 'किसानों को उनकी मिट्टी की पोषक स्थिति की जानकारी प्रदान करता है।', docs: ['मिट्टी का नमूना', 'आधार कार्ड', 'मोबाइल नंबर'] },
        { title: 'पीएम फसल बीमा योजना', provider: 'केंद्र सरकार', benefit: 'फसल बीमा', eligibility: 'KCC धारक', link: 'https://pmfby.gov.in/', details: 'एक राष्ट्र-एक योजना। यह फसल की विफलता के खिलाफ व्यापक बीमा प्रदान करता है।', docs: ['बुवाई प्रमाण पत्र', 'भूमि रिकॉर्ड', 'ID प्रमाण'] },
        { title: 'किसान क्रेडिट कार्ड (KCC)', provider: 'स्टेट बैंक', benefit: 'कम ब्याज ऋण', eligibility: 'पात्र किसान', link: 'https://www.myscheme.gov.in/schemes/kcc', details: 'किसानों को उनकी उत्पादन ऋण आवश्यकताओं को पूरा करने के लिए समय पर और पर्याप्त ऋण।', docs: ['आवेदन पत्र', 'भूमि दस्तावेज', 'पासपोर्ट फोटो'] },
        { title: 'कुसुम योजना', provider: 'MNRE', benefit: 'सोलर पंप सब्सिडी', eligibility: 'व्यक्तिगत किसान', link: 'https://pmkusum.mnre.gov.in/', details: 'स्टैंडअलोन सौर कृषि पंपों की स्थापना और मौजूदा ग्रिड-कनेक्टेड पंपों का सौरकरण।', docs: ['सोलर पंप आवेदन', 'पहचान प्रमाण', 'भूमि के कागजात'] },
        { title: 'एग्री-इंफ्रास्ट्रक्चर फंड', provider: 'केंद्र सरकार', benefit: 'भंडारण सब्सिडी', eligibility: 'स्टार्टअप और किसान', link: 'https://theagriculturefund.nic.in/', details: 'फसल कटाई के बाद के प्रबंधन बुनियादी ढांचे के लिए निवेश।', docs: ['DPR (विस्तृत परियोजना रिपोर्ट)', 'KYC दस्तावेज', 'बैंक ऋण स्वीकृति'] },
    ],
    // Hindi Dynamic
    "Paddy (Dhan)": "धान (चावल)",
    "Wheat": "गेहूं",
    "Cotton": "कपास",
    "Maize": "मक्का",
    "Tomato": "टमाटर",
    "Onion": "प्याज",
    "Potato": "आलू",
    "Chilli": "मिर्च",
    "Turmeric": "हल्दी",
    "Groundnut": "मूंगफली",
    "Soybean": "सोयाबीन",
    "Mustard": "सरसों",
    "Andhra Pradesh": "आंध्र प्रदेश",
    "Telangana": "तेलंगाना",
    "Karnataka": "कर्नाटक",
    "Maharashtra": "महाराष्ट्र",
    "Punjab": "पंजाब",
    "Uttar Pradesh": "उत्तर प्रदेश",
    "Madhya Pradesh": "मध्य प्रदेश",
    "Tamil Nadu": "तमिलनाडु",
    "Gujarat": "गुजरात",
    "Haryana": "हरियाणा"
};

// 3. Define Other Regional Languages

const te = {
    detect: "వ్యాధి నిర్ధారణ",
    dashboard: "డ్యాష్‌బోర్డ్",
    history: "చరిత్ర",
    weather: "వాతావరణం",
    mandi: "మార్కెట్ ధరలు",
    schemes: "పథకాలు",
    community: "రైతు వేదిక",
    login: "ఏజెంట్ లాగిన్",
    logout: "లాగ్ అవుట్",
    welcome: "మీ పంటలకు నిపుణుల రక్షణ",
    homeSubtitle: "వ్యాధులను గుర్తించండి, చికిత్స పొందండి మరియు నిమిషాల్లో నిపుణులను సంప్రదించండి.",
    startDiagnosis: "పరీక్ష ప్రారంభించండి",
    viewWeather: "వాతావరణం చూడండి",
    trustedBy: "20,000+ రైతుల నమ్మకం",
    accuracy: "98% కచ్చితత్వం",
    instantReport: "తక్షణ నివేదిక",
    expertHelp: "నిపుణుల సహాయం",
    aiCropDoctor: "AI పంట డాక్టర్",
    detectionSubtitle: "ఆకు ఫోటో తీయండి లేదా అప్‌లోడ్ చేయండి. మా AI వ్యాధులను గుర్తిస్తుంది.",
    readyToScan: "స్కాన్ చేయడానికి సిద్ధమా?",
    dropImage: "ఫోటోను ఇక్కడ వదలండి లేదా బ్రౌజ్ చేయండి",
    analyzeInfection: "వ్యాధిని విశ్లేషించండి",
    computing: "వ్యాధులను లెక్కిస్తోంది...",
    recommendedRecovery: "సూచించిన చికిత్స",
    biologicalMeasures: "సేంద్రీయ నివారణలు",
    saveToCloud: "నివేదికను భద్రపరచండి",
    today: 'ఈ రోజు',
    delete: 'తొలగించు',
    state: 'రాష్ట్రం',
    confirmDelete: 'మీరు ఖచ్చితంగా ఈ పోస్ట్‌ను తొలగించాలనుకుంటున్నారా?',
    mandiTitle: "తాజా మార్కెట్ ధరలు",
    mandiSubtitle: "భారతదేశం అంతటా మీ పంటల కోసం నిజ-సమయ మార్కెట్ ధరలను ట్రాక్ చేయండి.",
    cropName: "పంట పేరు",
    market: "మార్కెట్",
    price: "ధర (₹/క్వింటాల్)",
    trend: "సరళి",
    schemesTitle: "ప్రభుత్వ పథకాలు",
    schemesSubtitle: "రైతులకు అందుబాటులో ఉన్న ఆర్థిక సహాయం మరియు రాయితీలు.",
    applyNow: "దరఖాస్తు చేయండి",
    details: "వివరాలు",
    close: "మూసివేయు",
    aboutScheme: "పథకం గురించి",
    reqDocs: "కావలసిన పత్రాలు",
    communityTitle: "రైతు సంఘం",
    communitySubtitle: "తోటి రైతులతో చర్చించండి మరియు నేర్చుకోండి.",
    newPost: "చర్చను ప్రారంభించండి",
    replies: "సమాధానాలు",
    welcomeBack: "స్వాగతం",
    createAccount: "ఖాతా సృష్టించండి",
    secureLogin: "సురక్షిత వ్యవసాయ విశ్లేషణలు",
    googleLogin: "Googleతో కొనసాగండి",
    useEmail: "ఇమెయిల్ ఉపయోగించండి",
    email: "ఇమెయిల్",
    password: "పాస్‌వర్డ్",
    signIn: "సైన్ ఇన్",
    joinNow: "చేరండి",
    needAccount: "ఖాతా కావాలా?",
    existingMember: "లాగిన్ చేయండి",
    goodMorning: "శుభోదయం",
    goodAfternoon: "శుభ మధ్యాహ్నం",
    goodEvening: "శుభ సాయంత్రం",
    dashboardSubtitle: "ఈ రోజు మీ పంటల పరిస్థితి ఇక్కడ ఉంది.",
    overallHealth: "పంట ఆరోగ్యం",
    activeAlerts: "హెచ్చరికలు",
    tasksCompleted: "పూర్తయిన పనులు",
    performanceIndex: "పనితీరు",
    localWeather: "స్థానిక వాతావరణం",
    detailedForecast: "పూర్తి వివరాలు",
    detectionHistory: "పరీక్షల చరిత్ర",
    liveMarket: "తాజా ధరలు",
    updated: "నవీకరించబడింది",
    selectState: "రాష్ట్రాన్ని ఎంచుకోండి",
    searchMandi: "మార్కెట్/పంటను వెతకండి...",
    minPrice: "కనీస ధర",
    maxPrice: "గరిష్ట ధర",
    modalPrice: "సగటు ధర",
    searchCity: "నగరాన్ని వెతకండి...",
    humidity: "తేమ",
    windSpeed: "గాలి వేగం",
    precipitation: "వర్షపాతం",
    filterPlaceholder: "వెతకండి...",
    all: "అన్నీ",
    healthy: "ఆరోగ్యకరమైనవి",
    issues: "సమస్యలు",
    highSeverity: "తీవ్రమైనవి",
    loadingDiscussions: "లోడ్ అవుతోంది...",
    noDiscussions: "చర్చలు లేవు.",
    loadingRecords: "లోడ్ అవుతోంది...",
    noRecords: "డేటా లేదు",
    exportPDF: "PDF ఎగుమతి",
    confidence: "నమ్మకం",
    cloudSynced: "భద్రపరచబడింది",
    unknown: "తెలియదు",
    applyWebsite: "వెబ్‌సైట్‌లో దరఖాస్తు చేయండి",
    deleteSuccess: "తొలగించబడింది!",
    deleteFail: "విఫలమైంది...",
    newDiscussion: "కొత్త చర్చ",
    shareTip: "మీ ప్రశ్నను పంచుకోండి...",
    cancel: "రద్దు",
    post: "పోస్ట్",
    regionalGroups: "ప్రాంతీయ సమూహాలు",
    regionalSubtitle: "మీ భాషలో మాట్లాడండి",
    schemesData: [
        { title: 'PM- కిసాన్ సమ్మాన్ నిధి', provider: 'కేంద్ర ప్రభుత్వం', benefit: '₹6,000/ఏడాదికి', eligibility: 'చిన్న రైతులు', link: 'https://pmkisan.gov.in/', details: 'రైతు కుటుంబాలకు సంవత్సరానికి ₹6,000 ఆర్థిక సహాయం.', docs: ['ఆధార్ కార్డు', 'భూమి పత్రాలు', 'బ్యాంకు ఖాతా'] },
        { title: 'నేల ఆరోగ్య కార్డు', provider: 'వ్యవసాయ శాఖ', benefit: 'నేల పరీక్ష', eligibility: 'అందరూ రైతులు', link: 'https://soilhealth.dac.gov.in/', details: 'రైతులకు వారి నేల పోషక స్థితి గురించి సమాచారం.', docs: ['మట్టి నమూనా', 'ఆధార్', 'మొబైల్ నంబర్'] },
        { title: 'PM ఫసల్ బీమా యోజన', provider: 'కేంద్ర ప్రభుత్వం', benefit: 'పంట బీమా', eligibility: 'KCC రైతులు', link: 'https://pmfby.gov.in/', details: 'పంట నష్టానికి వ్యతిరేకంగా సమగ్ర బీమా కవరేజ్.', docs: ['పంట సాగు పత్రం', 'భూమి రికార్డులు', 'ID ప్రూఫ్'] },
        { title: 'కిసాన్ క్రెడిట్ కార్డు', provider: 'SBI', benefit: 'తక్కువ వడ్డీ రుణాలు', eligibility: 'అర్హులైన రైతులు', link: 'https://www.myscheme.gov.in/schemes/kcc', details: 'రైతులకు పంట సాగు కోసం రుణ సౌకర్యం.', docs: ['దరఖాస్తు ఫారం', 'భూమి పత్రాలు', 'ఫోటో'] },
        { title: 'కుసుమ్ పథకం', provider: 'MNRE', benefit: 'సోలార్ పంపులు', eligibility: 'రైతులు', link: 'https://pmkusum.mnre.gov.in/', details: 'సోలార్ వ్యవసాయ పంపుల ఏర్పాటుకు రాయితీ.', docs: ['దరఖాస్తు', 'గుర్తింపు కార్డు', 'భూమి పత్రాలు'] },
        { title: 'అగ్రి-ఇన్‌ఫ్రా ఫండ్', provider: 'కేంద్ర ప్రభుత్వం', benefit: 'గోదాము రాయితీ', eligibility: 'రైతులు', link: 'https://theagriculturefund.nic.in/', details: 'పంట నిల్వ మరియు మౌలిక సదుపాయాల కోసం రుణం.', docs: ['ప్రాజెక్ట్ రిపోర్ట్', 'KYC', 'బ్యాంకు ఆమోదం'] },
    ],
    // Telugu Dynamic
    "Paddy (Dhan)": "వరి (ధాన్యం)",
    "Wheat": "గోధుమలు",
    "Cotton": "పత్తి",
    "Maize": "మొక్కజొన్న",
    "Tomato": "టమాటా",
    "Onion": "ఉల్లిపాయలు",
    "Potato": "బంగాళాదుంప",
    "Chilli": "మిరపకాయలు",
    "Turmeric": "పసుపు",
    "Groundnut": "వేరుశెనగ",
    "Soybean": "సోయాబీన్",
    "Mustard": "ఆవాలు",
    "Andhra Pradesh": "ఆంధ్రప్రదేశ్",
    "Telangana": "తెలంగాణ",
    "Karnataka": "కర్ణాటక",
    "Maharashtra": "మహారాష్ట్ర",
    "Punjab": "పంజాబ్",
    "Uttar Pradesh": "ఉత్తర ప్రదేశ్",
    "Madhya Pradesh": "మధ్య ప్రదేశ్",
    "Tamil Nadu": "తమిళనాడు",
    "Gujarat": "గుజరాత్",
    "Haryana": "హర్యానా"
};

const kn = {
    detect: "ರೋಗ ಪತ್ತೆ",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    history: "ಇತಿಹಾಸ",
    weather: "ಹವಾಮಾನ",
    mandi: "ಮಾರುಕಟ್ಟೆ ಬೆಲೆ",
    schemes: "ಯೋಜನೆಗಳು",
    community: "ರೈತ ಸಮುದಾಯ",
    login: "ಏಜೆಂಟ್ ಲಾಗಿನ್",
    logout: "ಲಾಗ್ ಔಟ್",
    welcome: "ನಿಮ್ಮ ಬೆಳೆಗಳಿಗೆ ತಜ್ಞರ ರಕ್ಷಣೆ",
    homeSubtitle: "ರೋಗಗಳನ್ನು ಗುರುತಿಸಿ ಮತ್ತು ತಜ್ಞರ ಸಲಹೆ ಪಡೆಯಿರಿ.",
    startDiagnosis: "ಪರೀಕ್ಷಿಸಿ",
    viewWeather: "ಹವಾಮಾನ ವರದಿ",
    trustedBy: "20,000+ ರೈತರ ನಂಬಿಕೆ",
    accuracy: "98% ನಿಖರತೆ",
    instantReport: "ತಕ್ಷಣದ ವರದಿ",
    expertHelp: "ತಜ್ಞರ ಸಹಾಯ",
    aiCropDoctor: "AI ಕ್ರಾಪ್ ಡಾಕ್ಟರ್",
    detectionSubtitle: "ಎಲೆಯ ಫೋಟೋ ತೆಗೆಯಿರಿ. ನಮ್ಮ AI ರೋಗವನ್ನು ಪತ್ತೆ ಮಾಡುತ್ತದೆ.",
    readyToScan: "ಸ್ಕ್ಯಾನ್ ಮಾಡಲು ಸಿದ್ಧರಿದ್ದೀರಾ?",
    dropImage: "ಚಿತ್ರವನ್ನು ಇಲ್ಲಿ ಹಾಕಿ",
    analyzeInfection: "ವಿಶ್ಲೇಷಿಸಿ",
    computing: "ಲೆಕ್ಕಾಚಾರ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    recommendedRecovery: "ಶಿಫಾರಸು ಮಾಡಿದ ಚಿಕಿತ್ಸೆ",
    biologicalMeasures: "ಸಾವಯವ ಕ್ರಮಗಳು",
    saveToCloud: "ವರದಿ ಉಳಿಸಿ",
    today: 'ಇಂದು',
    delete: 'ಅಳಿಸಿ',
    state: 'ರಾಜ್ಯ',
    confirmDelete: 'ಈ ಪೋಸ್ಟ್ ಅನ್ನು ಅಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿದ್ದೀರಾ?',
    mandiTitle: "ಮಾರುಕಟ್ಟೆ ದರಗಳು",
    mandiSubtitle: "ಭಾರತದಾದ್ಯಂತ ನಿಮ್ಮ ಬೆಳೆಗಳ ಮಾರುಕಟ್ಟೆ ದರಗಳನ್ನು ತಿಳಿಯಿರಿ.",
    cropName: "ಬೆಳೆ ಹೆಸರು",
    market: "ಮಾರುಕಟ್ಟೆ",
    price: "ಬೆಳೆ (₹/ಕ್ವಿಂಟಾಲ್)",
    trend: "ಒಲವು",
    schemesTitle: "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
    schemesSubtitle: "ರೈತರಿಗೆ ಆರ್ಥಿಕ ಸಹಾಯ ಮತ್ತು ಸಬ್ಸಿಡಿಗಳು.",
    applyNow: "ಅರ್ಜಿ ಹಾಕಿ",
    details: "ವಿವರಗಳು",
    close: "ಮುಚ್ಚಿ",
    aboutScheme: "ಯೋಜನೆಯ ಬಗ್ಗೆ",
    reqDocs: "ಅಗತ್ಯ ದಾಖಲೆಗಳು",
    communityTitle: "ರೈತ ವೇದಿಕೆ",
    communitySubtitle: "ಸಹ ರೈತರೊಂದಿಗೆ ಚರ್ಚಿಸಿ.",
    newPost: "ಚರ್ಚೆ ಪ್ರಾರಂಭಿಸಿ",
    replies: "ಉತ್ತರಗಳು",
    welcomeBack: "ಸ್ವಾಗತ",
    createAccount: "ಖಾತೆ ರಚಿಸಿ",
    secureLogin: "ಸುರಕ್ಷಿತ ಲಾಗಿನ್",
    googleLogin: "Google ಜತೆ ಮುಂದುವರಿಯಿರಿ",
    useEmail: "ಇಮೇಲ್ ಬಳಸಿ",
    email: "ಇಮೇಲ್",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    signIn: "ಸೈನ್ ಇನ್",
    joinNow: "ಸೇರಿಕೊಳ್ಳಿ",
    needAccount: "ಖಾತೆ ಬೇಕೇ?",
    existingMember: "ಲಾಗಿನ್ ಆಗಿ",
    goodMorning: "ಶುಭೋದಯ",
    goodAfternoon: "ಶುಭ ಮಧ್ಯಾಹ್ನ",
    goodEvening: "ಶುಭ ಸಂಜೆ",
    dashboardSubtitle: "ನಿಮ್ಮ ಬೆಳೆಗಳ ಸ್ಥಿತಿ ಇಲ್ಲಿದೆ.",
    overallHealth: "ಬೆಳೆ ಆರೋಗ್ಯ",
    activeAlerts: "ಎಚ್ಚರಿಕೆಗಳು",
    tasksCompleted: "ಪೂರ್ಣಗೊಂಡ ಕಾರ್ಯಗಳು",
    performanceIndex: "ಕಾರ್ಯಕ್ಷಮತೆ",
    localWeather: "ಸ್ಥಳೀಯ ಹವಾಮಾನ",
    detailedForecast: "ಪೂರ್ಣ ವರದಿ",
    detectionHistory: "ಪತ್ತೆ ಇತಿಹಾಸ",
    liveMarket: "ಲೈವ್ ದರಗಳು",
    updated: "ನವೀಕರಿಸಲಾಗಿದೆ",
    selectState: "ರಾಜ್ಯ ಆಯ್ಕೆಮಾಡಿ",
    searchMandi: "ಹುಡುಕಿ...",
    minPrice: "ಕನಿಷ್ಠ ಬೆಲೆ",
    maxPrice: "ಗರಿಷ್ಠ ಬೆಲೆ",
    modalPrice: "ಸರಾಸರಿ ಬೆಲೆ",
    searchCity: "ನಗರ ಹುಡುಕಿ...",
    humidity: "ತೇವಾಂಶ",
    windSpeed: "ಗಾಳಿಯ ವೇಗ",
    precipitation: "ಮಳೆ",
    filterPlaceholder: "ಹುಡುಕಿ...",
    all: "ಎಲ್ಲಾ",
    healthy: "ಆರೋಗ್ಯಕರ",
    issues: "ಸಮಸ್ಯೆಗಳು",
    highSeverity: "ಗಂಭೀರ",
    loadingDiscussions: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    noDiscussions: "ಯಾವುದೇ ಚರ್ಚೆಗಳಿಲ್ಲ.",
    loadingRecords: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    noRecords: "ಮಾಹಿತಿ ಇಲ್ಲ",
    exportPDF: "PDF ಡೌನ್‌ಲೋಡ್",
    confidence: "ನಂಬಿಕೆ",
    cloudSynced: "ಕ್ಲೌಡ್ ಸಿಂಕ್",
    unknown: "ಗೊತ್ತಿಲ್ಲ",
    applyWebsite: "ವೆಬ್‌ಸೈಟ್‌ಗೆ ಭೇಟಿ ನೀಡಿ",
    deleteSuccess: "ಅಳಿಸಲಾಗಿದೆ!",
    deleteFail: "ವಿಫಲವಾಗಿದೆ...",
    newDiscussion: "ಹೊಸ ಚರ್ಚೆ",
    shareTip: "ಪ್ರಶ್ನೆ ಕೇಳಿ...",
    cancel: "ರದ್ದು",
    post: "ಪೋಸ್ಟ್",
    regionalGroups: "ಪ್ರಾದೇಶಿಕ ಗುಂಪುಗಳು",
    regionalSubtitle: "ಸ್ಥಳೀಯ ಭಾಷೆಯಲ್ಲಿ ಮಾತನಾಡಿ",
    schemesData: [
        { title: 'PM- ಕಿಸಾನ್ ಸಮ್ಮಾನ್ ನಿಧಿ', provider: 'ಕೇಂದ್ರ ಸರ್ಕಾರ', benefit: '₹6,000/ವರ್ಷಕ್ಕೆ', eligibility: 'ಸಣ್ಣ ರೈತರು', link: 'https://pmkisan.gov.in/', details: 'ರೈತ ಕುಟುಂಬಗಳಿಗೆ ವಾರ್ಷಿಕ ₹6,000 ಆರ್ಥಿಕ ಬೆಂಬಲ.', docs: ['ಆಧಾರ್ ಕಾರ್ಡ್', 'ಭೂಮಿ ದಾಖಲೆ', 'ಬ್ಯಾಂಕ್ ಖಾತೆ'] },
        { title: 'ಮಣ್ಣು ಆರೋಗ್ಯ ಕಾರ್ಡ್', provider: 'ಕೃಷಿ ಇಲಾಖೆ', benefit: 'ಮಣ್ಣು ಪರೀಕ್ಷೆ', eligibility: 'ಎಲ್ಲಾ ರೈತರು', link: 'https://soilhealth.dac.gov.in/', details: 'ಮಣ್ಣಿನ ಪೋಷಕಾಂಶಗಳ ಬಗ್ಗೆ ಮಾಹಿತಿ.', docs: ['ಮಣ್ಣಿನ ಮಾದರಿ', 'ಆಧಾರ್', 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ'] },
        { title: 'PM ಫಸಲ್ ಬಿಮಾ ಯೋಜನೆ', provider: 'ಕೇಂದ್ರ ಸರ್ಕಾರ', benefit: 'ಬೆಳೆ ವಿಮೆ', eligibility: 'KCC ಹೊಂದಿರುವವರು', link: 'https://pmfby.gov.in/', details: 'ಬೆಳೆ ನಷ್ಟದ ವಿರುದ್ಧ ವಿಮೆ.', docs: ['ಬಿತ್ತನೆ ಪ್ರಮಾಣಪತ್ರ', 'ಭೂಮಿ ದಾಖಲೆ', 'ID ಪುರಾವೆ'] },
        { title: 'ಕಿಸಾನ್ ಕ್ರೆಡಿಟ್ ಕಾರ್ಡ್', provider: 'SBI', benefit: 'ಕಡಿಮೆ ಬಡ್ಡಿ ಸಾಲ', eligibility: 'ಅರ್ಹ ರೈತರು', link: 'https://www.myscheme.gov.in/schemes/kcc', details: 'ಕೃಷಿ ಅಗತ್ಯಗಳಿಗಾಗಿ ಸಾಲ ಸೌಲಭ್ಯ.', docs: ['ಅರ್ಜಿ', 'ಭೂಮಿ ದಾಖಲೆ', 'ಫೋಟೋ'] },
        { title: 'ಕುಸುಮ್ ಯೋಜನೆ', provider: 'MNRE', benefit: 'ಸೌರ ಪಂಪ್‌ಗಳು', eligibility: 'ರೈತರು', link: 'https://pmkusum.mnre.gov.in/', details: 'ಸೌರ ಕೃಷಿ ಪಂಪ್‌ಗಳ ಅಳವಡಿಕೆಗೆ ಸಹಾಯಧನ.', docs: ['ಅರ್ಜಿ', 'ಗುರುತಿನ ಚೀಟಿ', 'ಭೂಮಿ ದಾಖಲೆ'] },
        { title: 'ಅಗ್ರಿ-ಇನ್ಫ್ರಾ ಫಂಡ್', provider: 'ಕೇಂದ್ರ ಸರ್ಕಾರ', benefit: 'ಗೋದಾಮು ಸಬ್ಸಿಡಿ', eligibility: 'ರೈತರು', link: 'https://theagriculturefund.nic.in/', details: 'ಕೊಯ್ಲು ನಂತರದ ನಿರ್ವಹಣೆಗೆ ಸಾಲ.', docs: ['ಯೋಜನಾ ವರದಿ', 'KYC', 'ಬ್ಯಾಂಕ್ ಅನುಮೋದನೆ'] },
    ],
    // Kannada Dynamic
    "Paddy (Dhan)": "ಭತ್ತ",
    "Wheat": "ಗೋಧಿ",
    "Cotton": "ಹತ್ತಿ",
    "Maize": "ಜೋಳ",
    "Tomato": "ಟೊಮ್ಯಾಟೊ",
    "Onion": "ಈರುಳ್ಳಿ",
    "Potato": "ಆಲೂಗಡ್ಡೆ",
    "Chilli": "ಮೆಣಸಿನಕಾಯಿ",
    "Turmeric": "ಅರಿಶಿನ",
    "Groundnut": "ಕಡಲೆಕಾಯಿ",
    "Soybean": "ಸೋಯಾಬೀನ್",
    "Mustard": "ಸಾಸಿವೆ",
    "Andhra Pradesh": "ಆಂಧ್ರಪ್ರದೇಶ",
    "Telangana": "ತೆಲಂಗಾಣ",
    "Karnataka": "ಕರ್ನಾಟಕ",
    "Maharashtra": "ಮಹಾರಾಷ್ಟ್ರ",
    "Punjab": "ಪಂಜಾಬ್",
    "Uttar Pradesh": "ಉತ್ತರ ಪ್ರದೇಶ",
    "Madhya Pradesh": "ಮಧ್ಯ ಪ್ರದೇಶ",
    "Tamil Nadu": "ತಮಿಳುನಾಡು",
    "Gujarat": "ಗುಜರಾತ್",
    "Haryana": "ಹರಿಯಾಣ"
};

const ta = {
    detect: "கண்டறிதல்",
    dashboard: "முகಪು",
    history: "வரலாறு",
    weather: "வானிலை",
    mandi: "சந்தை விலை",
    schemes: "திட்டங்கள்",
    community: "விவசாயி குழு",
    login: "ஏஜென்ட்",
    logout: "வெளியேறு",
    welcome: "நிபுணர் பாதுகாப்பு",
    homeSubtitle: "நோய்களைக் கண்டறிந்து நிபுணர்களுடன் ஆலோசிக்கவும்.",
    startDiagnosis: "தொடங்கவும்",
    viewWeather: "வானிலை பார்க்க",
    trustedBy: "20,000+ விவசாயிகளின் நம்பிக்கை",
    accuracy: "98% துல்லியம்",
    instantReport: "உடனடி அறிக்கை",
    expertHelp: "நிபுணர் உதவி",
    aiCropDoctor: "AI பயிர் மருத்துவர்",
    detectionSubtitle: "இலையின் புகைப்படத்தை எடுக்கவும். AI நோயைக் கண்டறியும்.",
    readyToScan: "ஸ்கேன் செய்யத் தயாரா?",
    dropImage: "படத்தை இங்கே போடவும்",
    analyzeInfection: "பகுப்பாய்வு",
    computing: "கணக்கிடுகிறது...",
    recommendedRecovery: "பரிந்துரைக்கப்பட்ட தீர்வு",
    biologicalMeasures: "இயற்கை முறைகள்",
    saveToCloud: "சேமிக்கவும்",
    today: 'இன்று',
    delete: 'நீக்கு',
    state: 'மாநிலம்',
    confirmDelete: 'இதை நீக்க விரும்புகிறீர்களா?',
    mandiTitle: "சந்தை நிலவரம்",
    mandiSubtitle: "நாடு முழுவதும் உள்ள சந்தை விலைகளை அறியவும்.",
    cropName: "பயிர் பெயர்",
    market: "சந்தை",
    price: "விலை (₹/குவிண்டால்)",
    trend: "போக்கு",
    schemesTitle: "அரசு திட்டங்கள்",
    schemesSubtitle: "விவசாயிகளுக்கான நிதியுதவி மற்றும் மானியங்கள்.",
    applyNow: "விண்ணப்பிக்கவும்",
    details: "விவரங்கள்",
    close: "மூடு",
    aboutScheme: "திட்டம் பற்றி",
    reqDocs: "தேவையான ஆவணங்கள்",
    communityTitle: "விவசாயக் குழு",
    communitySubtitle: "விவாதிக்கவும் மற்றும் பகிரவும்.",
    newPost: "புதிய விவாதம்",
    replies: "பதில்கள்",
    welcomeBack: "நல்வரவு",
    createAccount: "கணக்கை உருவாக்கு",
    secureLogin: "பாதுகாப்பான உள்நுழைவு",
    googleLogin: "Google மூலம் தொடரவும்",
    useEmail: "மின்னஞ்சல் பயன்படுத்தவும்",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    signIn: "உள்நுழையவும்",
    joinNow: "இணையவும்",
    needAccount: "புதிய கணக்கு?",
    existingMember: "உள்நுழையவும்",
    goodMorning: "காலை வணக்கம்",
    goodAfternoon: "மதிய வணக்கம்",
    goodEvening: "மாலை வணக்கம்",
    dashboardSubtitle: "உங்கள் பயிர்களின் நிலை.",
    overallHealth: "பயிர் ஆரோக்கியம்",
    activeAlerts: "எச்சரிக்கைகள்",
    tasksCompleted: "முடித்த பணிகள்",
    performanceIndex: "செயல்திறன்",
    localWeather: "உள்ளூர் வானிலை",
    detailedForecast: "முழு அறிக்கை",
    detectionHistory: "வரலாறு",
    liveMarket: "நேரடி விலை",
    updated: "புதுப்பிக்கப்பட்டது",
    selectState: "மாநிலம் தேர்வு",
    searchMandi: "தேடுக...",
    minPrice: "குறைந்தபட்சம்",
    maxPrice: "அதிகபட்சம்",
    modalPrice: "சராசரி விலை",
    searchCity: "நகரம் தேடுக...",
    humidity: "ஈரப்பதம்",
    windSpeed: "காற்றின் வேகம்",
    precipitation: "மழைப்பொழிவு",
    filterPlaceholder: "தேடுக...",
    all: "அனைத்தும்",
    healthy: "ஆரோக்கியம்",
    issues: "பிரச்சனைகள்",
    highSeverity: "தீவிரம்",
    loadingDiscussions: "ஏற்றப்படுகிறது...",
    noDiscussions: "விவாதங்கள் இல்லை.",
    loadingRecords: "ஏற்றப்படுகிறது...",
    noRecords: "தரவு இல்லை",
    exportPDF: "PDF பதிவிறக்கம்",
    confidence: "நம்பிக்கை",
    cloudSynced: "ஒத்திசைக்கப்பட்டது",
    unknown: "தெரியவில்லை",
    applyWebsite: "இணையதளத்தில் விண்ணப்பிக்கவும்",
    deleteSuccess: "நீக்கப்பட்டது!",
    deleteFail: "தோல்வி...",
    newDiscussion: "புதிய விவாதம்",
    shareTip: "கேள்வி கேட்கவும்...",
    cancel: "ரத்து",
    post: "பதிவிடு",
    regionalGroups: "பிராந்திய குழுக்கள்",
    regionalSubtitle: "உங்கள் மொழியில் பேசுங்கள்",
    schemesData: [
        { title: 'PM- கிசான் சம்மான் நிதி', provider: 'மத்திய அரசு', benefit: '₹6,000/ஆண்டு', eligibility: 'சிறு விவசாயிகள்', link: 'https://pmkisan.gov.in/', details: 'விவசாய குடும்பங்களுக்கு ஆண்டுக்கு ₹6,000 நிதியுதவி.', docs: ['ஆதார் அட்டை', 'நில ஆவணங்கள்', 'வங்கி கணக்கு'] },
        { title: 'மண் சுகாதார அட்டை', provider: 'வேளாண் துறை', benefit: 'மண் ஆய்வு', eligibility: 'அனைத்து விவசாயிகள்', link: 'https://soilhealth.dac.gov.in/', details: 'மண்ணின் சத்துக்கள் பற்றிய தகவல்.', docs: ['மண் மாதிரி', 'ஆதார்', 'மொபைல் எண்'] },
        { title: 'PM பயிர் காப்பீடு', provider: 'மத்திய அரசு', benefit: 'பயிர் காப்பீடு', eligibility: 'KCC வைத்திருப்போர்', link: 'https://pmfby.gov.in/', details: 'பயிர் இழப்புக்கு எதிரான காப்பீடு.', docs: ['விதைப்பு சான்றிதழ்', 'நில பதிவு', 'ID ஆதாரம்'] },
        { title: 'கிசான் கிரெடிட் கார்டு', provider: 'SBI', benefit: 'குறைந்த வட்டி கடன்', eligibility: 'தகுதிவாய்ந்த விவசாயிகள்', link: 'https://www.myscheme.gov.in/schemes/kcc', details: 'விவசாய தேவைகளுக்கான கடன் வசதி.', docs: ['விண்ணப்பம்', 'நில ஆவணங்கள்', 'புகைப்படம்'] },
        { title: 'குசும் திட்டம்', provider: 'MNRE', benefit: 'சூரிய பம்புகள்', eligibility: 'விவசாயிகள்', link: 'https://pmkusum.mnre.gov.in/', details: 'சூரிய சக்தி பம்புகளுக்கான மானியம்.', docs: ['விண்ணப்பம்', 'அடையாள அட்டை', 'நில ஆவணங்கள்'] },
        { title: 'வேளாண் உள்கட்டமைப்பு நிதி', provider: 'மத்திய அரசு', benefit: 'கிடங்கு மானியம்', eligibility: 'விவசாயிகள்', link: 'https://theagriculturefund.nic.in/', details: 'பயிர் சேமிப்புக்கான நிதியுதவி.', docs: ['திட்ட அறிக்கை', 'KYC', 'வங்கி ஒப்புதல்'] },
    ],
    // Tamil Dynamic
    "Paddy (Dhan)": "நெல்",
    "Wheat": "கோதுமை",
    "Cotton": "பருத்தி",
    "Maize": "சோளம்",
    "Tomato": "தக்காளி",
    "Onion": "வெங்காயம்",
    "Potato": "உருளைக்கிழங்கு",
    "Chilli": "மிளகாய்",
    "Turmeric": "மஞ்சள்",
    "Groundnut": "நிலக்கடலை",
    "Soybean": "சோயாபீன்",
    "Mustard": "கடுகு",
    "Andhra Pradesh": "ஆந்திர பிரதேசம்",
    "Telangana": "தெலுங்கானா",
    "Karnataka": "கர்நாடகா",
    "Maharashtra": "மகாராஷ்டிரா",
    "Punjab": "பஞ்சாப்",
    "Uttar Pradesh": "உத்தரப் பிரதேசம்",
    "Madhya Pradesh": "மத்தியப் பிரதேசம்",
    "Tamil Nadu": "தமிழ்நாடு",
    "Gujarat": "குஜராத்",
    "Haryana": "ஹரியானா"
};

const ml = {
    detect: "രോഗനിർണ്ണയം",
    dashboard: "ഡാഷ്ബോർഡ്",
    history: "ചരിത്രം",
    weather: "കാലാവസ്ഥ",
    mandi: "വിപണി വില",
    schemes: "പദ്ധതികൾ",
    community: "കർഷക കൂട്ടായ്മ",
    login: "ലോഗിൻ",
    logout: "പുറത്തുകടക്കുക",
    welcome: "വിളകൾക്ക് വിദഗ്ദ്ധ പരിചരണം",
    homeSubtitle: "രോഗങ്ങൾ തിരിച്ചറിയുക, വിദഗ്ധരുമായി സംസാരിക്കുക.",
    startDiagnosis: "പരിശോധന തുടങ്ങുക",
    viewWeather: "കാലാവസ്ഥ അറിയുക",
    trustedBy: "20,000+ കർഷകർ വിശ്വസിക്കുന്നു",
    accuracy: "98% കൃത്യത",
    instantReport: "പെട്ടെന്നുള്ള റിപ്പോർട്ട്",
    expertHelp: "വിദഗ്ദ്ധ സഹായം",
    aiCropDoctor: "AI ക്രോപ്പ് ഡോക്ടർ",
    detectionSubtitle: "ഇലയുടെ ഫോട്ടോ എടുക്കുക. AI രോഗം കണ്ടെത്തും.",
    readyToScan: "സ്കാൻ ചെയ്യാൻ തയ്യാറാണോ?",
    dropImage: "ചിത്രം ഇവിടെ നൽകുക",
    analyzeInfection: "വിശകലനം ചെയ്യുക",
    computing: "പരിശോധിക്കുന്നു...",
    recommendedRecovery: "ശുപാർശ ചെയ്യുന്ന ചികിത്സ",
    biologicalMeasures: "ജൈവ മാർഗ്ഗങ്ങൾ",
    saveToCloud: "റിപ്പോർട്ട് സൂക്ഷിക്കുക",
    today: 'ഇന്ന്',
    delete: 'നീക്കം ചെയ്യുക',
    state: 'സംസ്ഥാനം',
    confirmDelete: 'ഇത് നീക്കം ചെയ്യാൻ ആഗ്രഹിക്കുന്നുവോ?',
    mandiTitle: "വിപണി നിരക്കുകൾ",
    mandiSubtitle: "വിളകളുടെ തത്സമയ വിപണി വിലകൾ അറിയുക.",
    cropName: "വിള",
    market: "വിപണി",
    price: "വില (₹/ക്വിന്റൽ)",
    trend: "പ്രവണത",
    schemesTitle: "സർക്കാർ പദ്ധതികൾ",
    schemesSubtitle: "കർഷകർക്കുള്ള ധനസഹായവും സബ്‌സിഡിയും.",
    applyNow: "അപേക്ഷിക്കുക",
    details: "വിശദാംശങ്ങൾ",
    close: "അടയ്ക്കുക",
    aboutScheme: "പദ്ധതിയെക്കുറിച്ച്",
    reqDocs: "ആവശ്യമായ രേഖകൾ",
    communityTitle: "കർഷക വേദി",
    communitySubtitle: "ചർച്ച ചെയ്യുക, പങ്കിടുക.",
    newPost: "ചർച്ച തുടങ്ങുക",
    replies: "മറുപടികൾ",
    welcomeBack: "സ്വാഗതം",
    createAccount: "അക്കൗണ്ട് ഉണ്ടാക്കുക",
    secureLogin: "സുരക്ഷിത ലോഗിൻ",
    googleLogin: "Google വഴി തുടരുക",
    useEmail: "ഇമെയിൽ ഉപയോഗിക്കുക",
    email: "ഇമെയിൽ",
    password: "പാസ്‌വേഡ്",
    signIn: "സൈൻ ഇൻ",
    joinNow: "ചേരുക",
    needAccount: "അക്കൗണ്ട് വേണോ?",
    existingMember: "ലോഗിൻ ചെയ്യൂ",
    goodMorning: "സുപ്രഭാതം",
    goodAfternoon: "ശുഭ മദ്ധ്യാഹ്നം",
    goodEvening: "ശുഭ സന്ധ്യ",
    dashboardSubtitle: "നിങ്ങളുടെ വിളകളുടെ അവസ്ഥ.",
    overallHealth: "വിള ആരോഗ്യം",
    activeAlerts: "അറിയിപ്പുകൾ",
    tasksCompleted: "പൂർത്തിയാക്കിയവ",
    performanceIndex: "പ്രകടനം",
    localWeather: "പ്രാദേശിക കാലാവസ്ഥ",
    detailedForecast: "വിശദമായ റിപ്പോർട്ട്",
    detectionHistory: "പരിശോധന ചരിത്രം",
    liveMarket: "തത്സമയ വില",
    updated: "പുതുക്കിയത്",
    selectState: "സംസ്ഥാനം തിരഞ്ഞെടുക്കുക",
    searchMandi: "തിരയുക...",
    minPrice: "കുറഞ്ഞ വില",
    maxPrice: "കൂടിയ വില",
    modalPrice: "ശരാശരി വില",
    searchCity: "നഗരം തിരയുക...",
    humidity: "ഈർപ്പം",
    windSpeed: "കാറ്റിന്റെ വേഗത",
    precipitation: "മഴ",
    filterPlaceholder: "തിരയുക...",
    all: "എല്ലാം",
    healthy: "ആരോഗ്യമുള്ളവ",
    issues: "പ്രശ്നങ്ങൾ",
    highSeverity: "ഗുരുതരം",
    loadingDiscussions: "ലോഡുചെയ്യുന്നു...",
    noDiscussions: "ചർച്ചകൾ ഇല്ല.",
    loadingRecords: "ശേഖരിക്കുന്നു...",
    noRecords: "വിവരങ്ങൾ ഇല്ല",
    exportPDF: "PDF ഡൗൺലോഡ്",
    confidence: "വിശ്വാസ്യത",
    cloudSynced: "സിങ്ക് ചെയ്തു",
    unknown: "അജ്ഞാതം",
    applyWebsite: "വെബ്‌സൈറ്റിൽ അപേക്ഷിക്കുക",
    deleteSuccess: "നീക്കം ചെയ്തു!",
    deleteFail: "പരാജയപ്പെട്ടു...",
    newDiscussion: "പുതിയ ചർച്ച",
    shareTip: "ചോദ്യം ചോദിക്കുക...",
    cancel: "റദ്ദാക്കുക",
    post: "പോസ്റ്റ്",
    regionalGroups: "പ്രാദേശിക ഗ്രൂപ്പുകൾ",
    regionalSubtitle: "സ്വന്തം ഭാഷയിൽ സംസാരിക്കൂ",
    schemesData: [
        { title: 'പിഎം-കിസಾನ್ സമ്മാൻ നിധി', provider: 'കേന്ദ്ര സർക്കാർ', benefit: '₹6,000/വർഷം', eligibility: 'ചെറുകിട കർഷകർ', link: 'https://pmkisan.gov.in/', details: 'കർഷക കുടുംബങ്ങൾക്ക് വർഷം 6,000 രൂപ ധനസഹായം.', docs: ['ആധാർ കാർഡ്', 'ഭൂമി രേഖകൾ', 'ബാങ്ക് അക്കൗണ്ട്'] },
        { title: 'സോയിൽ ഹെൽത്ത് കാർഡ്', provider: 'കൃഷി വകുപ്പ്', benefit: 'മണ്ണ് പരിശോധന', eligibility: 'എല്ലാ കർഷകർക്കും', link: 'https://soilhealth.dac.gov.in/', details: 'മണ്ണിലെ പോഷകങ്ങളെക്കുറിച്ചുള്ള വിവരങ്ങൾ.', docs: ['മണ്ണ് സാമ്പിൾ', 'ആധാർ', 'മൊബൈൽ നമ്പർ'] },
        { title: 'പിഎം ഫസൽ ബീമാ യോജന', provider: 'കേന്ദ്ര സർക്കാർ', benefit: 'വിള ഇൻഷുറൻസ്', eligibility: 'KCC ഉള്ളവർക്ക്', link: 'https://pmfby.gov.in/', details: 'വിളനാശത്തിനെതിരായ സംരക്ഷണം.', docs: ['കൃഷി സർട്ടിഫിക്കറ്റ്', 'ഭൂമി രേഖ', 'ID കാർഡ്'] },
        { title: 'കിസാൻ ക്രെഡിറ്റ് കാർഡ്', provider: 'SBI', benefit: 'കുറഞ്ഞ പലിശക്ക് വായ്പ', eligibility: 'യോഗ്യരായ കർഷകർ', link: 'https://www.myscheme.gov.in/schemes/kcc', details: 'കൃഷി ആവശ്യങ്ങൾക്കുള്ള വായ്പാ സൗകര്യം.', docs: ['അപേക്ഷ', 'ഭൂമി രേഖകൾ', 'ഫോട്ടോ'] },
        { title: 'കുസും പദ്ധതി', provider: 'MNRE', benefit: 'സോളാർ പമ്പുകൾ', eligibility: 'കർഷകർ', link: 'https://pmkusum.mnre.gov.in/', details: 'സോളാർ പമ്പുകൾ സ്ഥാപിക്കുന്നതിനുള്ള സബ്‌സിഡി.', docs: ['അപേക്ഷ', 'തിരിച്ചറിയൽ കാർഡ്', 'ഭൂമി രേഖകൾ'] },
        { title: 'അഗ്രി-ഇൻഫ്രാ ഫണ്ട്', provider: 'കേന്ദ്ര സർക്കാർ', benefit: 'സംഭരണ സബ്‌സിഡി', eligibility: 'കർഷകർ', link: 'https://theagriculturefund.nic.in/', details: 'വിളവെടുപ്പിന് ശേഷമുള്ള സൗകര്യങ്ങൾക്കായി വായ്പ.', docs: ['പദ്ധതി രേഖ', 'KYC', 'ബാങ്ക് അംഗീകാരം'] },
    ],
    // Malayalam Dynamic
    "Paddy (Dhan)": "നെല്ല്",
    "Wheat": "ഗോതമ്പ്",
    "Cotton": "പരുത്തി",
    "Maize": "ചോളം",
    "Tomato": "തക്കാളി",
    "Onion": "ഉള്ളി",
    "Potato": "ഉരുളക്കിഴങ്ങ്",
    "Chilli": "മുളക്",
    "Turmeric": "മഞ്ഞൾ",
    "Groundnut": "നിലക്കടല",
    "Soybean": "സോയാബീൻ",
    "Mustard": "കടുക്",
    "Andhra Pradesh": "ആന്ധ്രാപ്രദേശ്",
    "Telangana": "തെലങ്കാന",
    "Karnataka": "കർണാടക",
    "Maharashtra": "മഹാരാഷ്ട്ര",
    "Punjab": "പഞ്ചാബ്",
    "Uttar Pradesh": "ഉത്തർപ്രദേശ്",
    "Madhya Pradesh": "മധ്യപ്രദേശ്",
    "Tamil Nadu": "തമിഴ്നാട്",
    "Gujarat": "ഗുജറാത്ത്",
    "Haryana": "ഹരിയാന",
    allIndiaCommunity: "അഖിലേന്ത്യ കമ്മ്യൂണിറ്റി",
    discussNation: "രാജ്യത്തുടനീളമുള്ള കർഷകരുമായി ചർച്ച ചെയ്യുക",
    tabAllIndia: "മുഴുവൻ ഇന്ത്യ",
    tabSolutions: "പരിഹാരങ്ങൾ",
    tabMyRegion: "എന്റെ പ്രദേശം",
    genDiscussion: "പൊതു ചർച്ച",
    suggSolution: "നിർദ്ദേശം / പരിഹാരം",
    solutionBadge: "പരിഹാരം",
    suggestedSol: "നിർദ്ദേശിച്ച പരിഹാരം",
    writeComment: "കമന്റ് എഴുതുക...",
    noDiscussionsCat: "ഈ വിഭാഗത്തിൽ ചർച്ചകളില്ല.",
    justNow: "ഇപ്പോൾ"
};

// 4. Create Context
const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    // Default to English if no valid language found
    const savedLang = localStorage.getItem('language');
    const [lang, setLang] = useState(savedLang || 'en');

    // Update localStorage when language changes
    React.useEffect(() => {
        localStorage.setItem('language', lang);
    }, [lang]);

    const translations = {
        en: {
            ...en,
            allIndiaCommunity: "All India Community",
            discussNation: "Discuss ideas & solutions with farmers across the nation",
            tabAllIndia: "All India",
            tabSolutions: "Solutions",
            tabMyRegion: "My Region",
            genDiscussion: "General Discussion",
            suggSolution: "Suggestion / Solution",
            solutionBadge: "Solution",
            suggestedSol: "Suggested Solution",
            writeComment: "Write a comment...",
            noDiscussionsCat: "No discussions found in this category.",
            justNow: "Just now"
        },
        hi: {
            ...hi,
            allIndiaCommunity: "अखिल भारतीय समुदाय",
            discussNation: "देश भर के किसानों के साथ विचारों और समाधानों पर चर्चा करें",
            tabAllIndia: "पूरी भारत",
            tabSolutions: "समाधान",
            tabMyRegion: "मेरा क्षेत्र",
            genDiscussion: "सामान्य चर्चा",
            suggSolution: "सुझाव / समाधान",
            solutionBadge: "समाधान",
            suggestedSol: "सुझाया गया समाधान",
            writeComment: "एक टिप्पणी लिखें...",
            noDiscussionsCat: "इस श्रेणी में कोई चर्चा नहीं मिली।",
            justNow: "अभी"
        },
        te: {
            ...te,
            allIndiaCommunity: "అఖిల భారత సంఘం",
            discussNation: "దేశవ్యాప్తంగా ఉన్న రైతుల తో చర్చించండి",
            tabAllIndia: "మొత్తం భారతదేశం",
            tabSolutions: "పరిష్కారాలు",
            tabMyRegion: "నా ప్రాంతం",
            genDiscussion: "సాధారణ చర్చ",
            suggSolution: "సూచన / పరిష్కారం",
            solutionBadge: "పరిష్కారం",
            suggestedSol: "సూచించిన పరిష్కారం",
            writeComment: "వ్యాఖ్య రాయండి...",
            noDiscussionsCat: "ఈ వర్గంలో చర్చలు లేవు.",
            justNow: "ఇప్పుడే"
        },
        kn: {
            ...kn,
            allIndiaCommunity: "ಅಖಿಲ ಭಾರತ ಸಮುದಾಯ",
            discussNation: "ದೇಶದಾದ್ಯಂತದ ರೈತರೊಂದಿಗೆ ಚರ್ಚಿಸಿ",
            tabAllIndia: "ಇಡೀ ಭಾರತ",
            tabSolutions: "ಪರಿಹಾರಗಳು",
            tabMyRegion: "ನನ್ನ ಪ್ರದೇಶ",
            genDiscussion: "ಸಾಮಾನ್ಯ ಚರ್ಚೆ",
            suggSolution: "ಸಲಹೆ / ಪರಿಹಾರ",
            solutionBadge: "ಪರಿಹಾರ",
            suggestedSol: "ಸೂಚಿಸಿದ ಪರಿಹಾರ",
            writeComment: "ಟಿಪ್ಪಣಿ ಬರೆಯಿರಿ...",
            noDiscussionsCat: "ಈ ವರ್ಗದಲ್ಲಿ ಯಾವುದೇ ಚರ್ಚೆಗಳಿಲ್ಲ.",
            justNow: "ಈಗಷ್ಟೇ"
        },
        ta: {
            ...ta,
            allIndiaCommunity: "அனைத்து இந்திய சமூகம்",
            discussNation: "நாடு முழுவதும் உள்ள விவசாயிகளுடன் விவாதிக்கவும்",
            tabAllIndia: "அனைத்து இந்தியா",
            tabSolutions: "தீர்வுகள்",
            tabMyRegion: "என் பகுதி",
            genDiscussion: "பொது விவாதம்",
            suggSolution: "பரிந்துரை / தீர்வு",
            solutionBadge: "தீர்வு",
            suggestedSol: "பரிந்துரைக்கப்பட்ட தீர்வு",
            writeComment: "கருத்து எழுதுங்கள்...",
            noDiscussionsCat: "இந்த வகையில் விவாதங்கள் இல்லை.",
            justNow: "இப்போது தான்"
        },
        ml: {
            ...ml,
            allIndiaCommunity: "അഖിലേന്ത്യ കമ്മ്യൂണിറ്റി",
            discussNation: "രാജ്യത്തുടനീളമുള്ള കർഷകരുമായി ചർച്ച ചെയ്യുക",
            tabAllIndia: "മുഴുവൻ ഇന്ത്യ",
            tabSolutions: "പരിഹാരങ്ങൾ",
            tabMyRegion: "എന്റെ പ്രദേശം",
            genDiscussion: "പൊതു ചർച്ച",
            suggSolution: "നിർദ്ദേശം / പരിഹാരം",
            solutionBadge: "പരിഹാരം",
            suggestedSol: "നിർദ്ദേശിച്ച പരിഹാരം",
            writeComment: "കമന്റ് എഴുതുക...",
            noDiscussionsCat: "ഈ വിഭാഗത്തിൽ ചർച്ചകളില്ല.",
            justNow: "ഇപ്പോൾ"
        }
    };

    const t = (key) => {
        return translations[lang][key] || translations['en'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ lang, setLang, t, translations: translations[lang] }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
