import React, { createContext, useState, useContext } from 'react';

// 1. Define Base English Translations
const en = {
    detect: "Detect",
    dashboard: "Dashboard",
    history: "History",
    weather: "Weather",
    mandi: "Mandi Prices",
    schemes: "Gov Schemes",
    community: "Community",
    login: "Agent Portal",
    logout: "Sign Out",
    fertilizerCalc: "Fertilizer Calculator",
    financialTracker: "Profit Tracker",
    agriShops: "Agri-Shops",
    verified: "Verified",
    distance: "Distance",
    nearbyShops: "Verified Agri-Shops Nearby",
    browseProducts: "Browse Products",
    alerts: "Outbreak Alerts",
    plotSize: "Plot Size",
    acre: "Acre",
    calculate: "Calculate",
    urea: "Urea",
    dap: "DAP",
    mop: "MOP",
    totalRequirement: "Total Requirement",
    initialInvestment: "Initial Investment",
    salePrice: "Anticipated Sale Price",
    otherExpenses: "Other Expenses",
    profit: "Profit",
    loss: "Loss",
    estimatedNetProfit: "Estimated Net Profit",
    welcome: "Expert Care for Your Crops",
    homeSubtitle: "Identify diseases, get treatment plans, and consult with experts in seconds.",
    startDiagnosis: "Start Diagnosis",
    viewWeather: "View Weather",
    trustedBy: "Trusted by 20,000+ Farmers",
    accuracy: "98% Accuracy",
    instantReport: "Instant Report",
    expertHelp: "Expert Help",
    aiCropDoctor: "AI Crop Doctor",
    detectionSubtitle: "Capture or upload a leaf photo. Our AI identifies pathologies.",
    readyToScan: "Ready to Scan?",
    dropImage: "Drop image or click to browse",
    analyzeInfection: "Analyze Infection",
    computing: "Computing Pathologies...",
    recommendedRecovery: "Recommended Recovery",
    biologicalMeasures: "Biological Measures",
    saveToCloud: "Commit Report to Cloud",
    today: 'Today',
    delete: 'Delete',
    state: 'State',
    confirmDelete: 'Are you sure you want to delete this post?',
    mandiTitle: "Live Mandi Prices",
    mandiSubtitle: "Track real-time market rates for your crops across India.",
    cropName: "Crop Name",
    market: "Market",
    price: "Price (₹/Quintal)",
    trend: "Trend",
    schemesTitle: "Government Schemes",
    schemesSubtitle: "Financial aid and subsidies available for farmers.",
    applyNow: "Apply Now",
    details: "View Details",
    close: "Close",
    aboutScheme: "About Scheme",
    reqDocs: "Required Documents",
    communityTitle: "Farmer Community",
    communitySubtitle: "Discuss, share, and learn from fellow farmers.",
    newPost: "Start Discussion",
    replies: "Replies",
    welcomeBack: "Welcome Back",
    createAccount: "Create Account",
    secureLogin: "Access secure agricultural analytics",
    googleLogin: "Continue with Google",
    useEmail: "Or use email",
    email: "Email",
    password: "Password",
    signIn: "Sign In",
    joinNow: "Join Now",
    needAccount: "Need an account? New Registry",
    existingMember: "Existing Member? Secure Login",
    goodMorning: "Good Morning",
    goodAfternoon: "Good Afternoon",
    goodEvening: "Good Evening",
    dashboardSubtitle: "Here's what's happening with your crops today.",
    overallHealth: "Overall Crop Health",
    activeAlerts: "Active Alerts",
    tasksCompleted: "Tasks Completed",
    performanceIndex: "Performance Index",
    localWeather: "Local Weather",
    detailedForecast: "View Detailed Forecast",
    detectionHistory: "Detection History",
    liveMarket: "Live Market Rates",
    updated: "Updated",
    selectState: "Select State",
    searchMandi: "Search Market/Crop...",
    forecast: "Market Forecast",
    advice: "AI Suggestion",
    sellNow: "SELL NOW",
    hold: "HOLD STOCK",
    trendRising: "Prices likely to rise ↑",
    trendFalling: "Prices may fall ↓",
    trendStable: "Market stable",
    reasonRising: "High demand expected next week",
    reasonFalling: "Supply surplus expected",
    reasonStable: "No fluctuations observed",
    minPrice: "Min Price",
    maxPrice: "Max Price",
    modalPrice: "Modal Price",
    searchCity: "Search City...",
    humidity: "Humidity",
    windSpeed: "Wind Speed",
    precipitation: "Precipitation",
    filterPlaceholder: "Search crop or disease...",
    all: "All",
    healthy: "Healthy",
    issues: "Issues Detected",
    highSeverity: "High Severity",
    loadingDiscussions: "Loading Discussions...",
    noDiscussions: "No active discussions yet.",
    loadingRecords: "Fetching Records...",
    noRecords: "No records found matching your filters",
    exportPDF: "Export PDF",
    confidence: "Confidence",
    cloudSynced: "Cloud Synced",
    unknown: "Unknown",
    applyWebsite: "Apply on Official Website",
    deleteSuccess: "Record deleted successfully!",
    deleteFail: "Failed to delete...",
    newDiscussion: "New Discussion",
    shareTip: "Share your farming query or tip...",
    cancel: "Cancel",
    post: "Post",
    regionalGroups: "Regional Groups",
    regionalSubtitle: "Connect with farmers in your local language",
    howItWorks: "How It Works",
    singleSubject: "Single Subject",
    singleSubjectDesc: "Ensure the leaf is the main focus.",
    naturalLight: "Natural Light",
    naturalLightDesc: "Use good lighting for best results.",
    highContext: "High Context",
    highContextDesc: "Capture enough surrounding details.",

    // Result Translations
    "Healthy": "Healthy",
    "High": "High",
    "Medium": "Medium",
    "Low": "Low",
    "None": "None",
    "General Plant": "General Plant",
    "Multiple Crops": "Multiple Crops",
    "Beans / General": "Beans / General",
    "Tomato / Potato / Cotton": "Tomato / Potato / Cotton",
    "Corn / Wheat": "Corn / Wheat",
    "General": "General",
    "Tomato / Wheat": "Tomato / Wheat",
    "Berries / Beans": "Berries / Beans",
    "Tomato": "Tomato",
    "Potato": "Potato",
    "CropAdvisory": "Crop Advisory",
    "organicSolutions": "Organic Solutions",
    "healthyMessageTitle": "Great News! Your plant appears healthy.",
    "healthyMessageBody": "Continue regular monitoring and care for best results.",
    "Powdery Mildew": "Powdery Mildew",
    "Bacterial Blight": "Bacterial Blight",
    "Verticillium Wilt": "Verticillium Wilt",
    "Leaf Rust": "Leaf Rust",
    "Viral Mosaic / Chlorosis": "Viral Mosaic / Chlorosis",
    "Septoria Leaf Spot": "Septoria Leaf Spot",
    "Anthracnose (Bird's Eye Spot)": "Anthracnose (Bird's Eye Spot)",
    "Tomato Leaf Mold": "Tomato Leaf Mold",
    "Potato Late Blight": "Potato Late Blight",
    "Not a Crop": "Not a Crop",

    schemesData: [
        { title: 'PM-Kisan Samman Nidhi', provider: 'Central Govt', benefit: '₹6,000/year', eligibility: 'Small/Marginal Farmers', link: 'https://pmkisan.gov.in/', details: 'Income support of ₹6,000 per year in three equal installments to all land holding farmer families.', docs: ['Aadhaar Card', 'Land Ownership Records', 'Bank Account Details'] },
        { title: 'PM Fasal Bima Yojana', provider: 'Central Govt', benefit: 'Crop Insurance', eligibility: 'KCC Holders', link: 'https://pmfby.gov.in/', details: 'Comprehensive insurance coverage against non-preventable natural risks from pre-sowing to post-harvest.', docs: ['Sowing Certificate', 'Land Records', 'ID Proof'] },
        { title: 'Kisan Credit Card (KCC)', provider: 'State Bank', benefit: 'Low-interest Loans', eligibility: 'Credit Worthy Farmers', link: 'https://www.myscheme.gov.in/schemes/kcc', details: 'Timely and adequate credit to farmers to meet their production credit requirements with interest subvention.', docs: ['Application Form', 'Land Documents', 'Passport Photo'] },
        { title: 'PM-KUSUM Scheme', provider: 'MNRE', benefit: 'Solar Pump Subsidies', eligibility: 'Individual Farmers', link: 'https://pmkusum.mnre.gov.in/', details: 'Subsidies for installing standalone solar pumps and solarizing existing grid-connected agriculture pumps.', docs: ['Solar Pump Application', 'Identity Proof', 'Land Papers'] },
        { title: 'Agri-Infrastructure Fund', provider: 'Central Govt', benefit: 'Post-Harvest Loans', eligibility: 'Startups & Farmers', link: 'https://theagriculturefund.nic.in/', details: 'Financing facility for investment in projects for post-harvest management infrastructure and community farming assets.', docs: ['DPR', 'KYC Documents', 'Bank Loan Approval'] },
        { title: 'PM-KMY (Pension Scheme)', provider: 'Central Govt', benefit: '₹3,000/month Pension', eligibility: 'Small Farmers (18-40 yrs)', link: 'https://maandhan.in/', details: 'Voluntary pension scheme assuring ₹3,000 monthly pension after reaching 60 years of age.', docs: ['Aadhaar Card', 'Savings Bank Account'] },
        { title: 'Clean Plant Programme', provider: 'Horticulture Board', benefit: 'Disease-free Material', eligibility: 'Horticulture Farmers', link: 'https://www.nhb.gov.in/', details: 'Access to disease-free, high-quality planting material for high-value horticulture crops.', docs: ['Land Records', 'Farmer Reg ID'] },
        { title: 'Digital Agriculture Mission', provider: 'Ministry of Agri', benefit: 'Digital Services', eligibility: 'All Farmers', link: 'https://agriwelfare.gov.in/', details: 'Unified digital infrastructure providing better access to soil data, market intel, and crop estimation.', docs: ['Aadhaar Card', 'Mobile Number'] },
    ],
    // Dynamic Data Keys (Crops & States) - English (Base)
    "Paddy (Dhan)": "Paddy (Dhan)",
    "Wheat": "Wheat",
    "Cotton": "Cotton",
    "Maize": "Maize",

    "Onion": "Onion",

    "Chilli": "Chilli",
    "Turmeric": "Turmeric",
    "Groundnut": "Groundnut",
    "Soybean": "Soybean",
    "Mustard": "Mustard",
    "Andhra Pradesh": "Andhra Pradesh",
    "Telangana": "Telangana",
    "Karnataka": "Karnataka",
    "Maharashtra": "Maharashtra",
    "Punjab": "Punjab",
    "Uttar Pradesh": "Uttar Pradesh",
    "Madhya Pradesh": "Madhya Pradesh",
    "Tamil Nadu": "Tamil Nadu",
    "Gujarat": "Gujarat",
    "Haryana": "Haryana",
    noCropDetected: "No Crop Detected",
    noCropDetectedDesc: "This system only analyzes field crops. Please upload a clear photo of a crop leaf or stem.",
    tryAnotherImage: "Scan Another Image",
    severity: "Severity",
    // Recommendations
    "Copper-based bactericides (preventative)": "Copper-based bactericides (preventative)",
    "Streptomycin (limited use)": "Streptomycin (limited use)",
    "Use disease-free seeds": "Use disease-free seeds",
    "Practice crop rotation": "Practice crop rotation",
    "Avoid working in wet fields": "Avoid working in wet fields",
    "Disinfect tools regularly": "Disinfect tools regularly",
    "Copper soap": "Copper soap",
    "Biological controls (Bacillus subtilis)": "Biological controls (Bacillus subtilis)",
    "Remove infected leaves immediately": "Remove infected leaves immediately",
    "Sulfur-based fungicides": "Sulfur-based fungicides",
    "Neem oil": "Neem oil",
    "Mancozeb": "Mancozeb",
    "Water at roots": "Water at roots",
    "Improve air circulation": "Improve air circulation"
};

// 2. Hindi Overrides
const hi = {
    detect: "पहचानें",
    dashboard: "डैशबोर्ड",
    history: "इतिहास",
    weather: "मौसम",
    mandi: "मंडी भाव",
    schemes: "सरकारी योजनाएं",
    community: "समुदाय",
    login: "एजेंट पोर्टल",
    logout: "लॉग आउट",
    fertilizerCalc: "खाद कैलकुलेटर",
    financialTracker: "लाभ ट्रैकर",
    agriShops: "कृषि दुकानें",
    verified: "सत्यापित",
    distance: "दूरी",
    nearbyShops: "आसपास की सत्यापित कृषि दुकानें",
    browseProducts: "उत्पाद देखें",
    alerts: "बीमारी अलर्ट",
    plotSize: "प्लॉट का आकार",
    acre: "एकड़",
    calculate: "गणना करें",
    urea: "यूरिया",
    dap: "डीएपी",
    mop: "एमओपी",
    totalRequirement: "कुल आवश्यकता",
    initialInvestment: "प्रारंभिक निवेश",
    salePrice: "अनुमानित बिक्री मूल्य",
    otherExpenses: "अन्य खर्चे",
    profit: "लाभ",
    loss: "हानि",
    estimatedNetProfit: "अनुमानित शुद्ध लाभ",
    welcome: "आपकी फसलों के लिए विशेषज्ञ देखभाल",
    homeSubtitle: "रोगों की पहचान करें, उपचार योजनाएं प्राप्त करें और विशेषज्ञों से सलाह लें।",
    startDiagnosis: "जांच शुरू करें",
    viewWeather: "मौसम देखें",
    trustedBy: "20,000+ किसानों द्वारा विश्वसनीय",
    accuracy: "98% सटीकता",
    instantReport: "तत्काल रिपोर्ट",
    expertHelp: "विशेषज्ञ सहायता",
    aiCropDoctor: "AI फसल डॉक्टर",
    detectionSubtitle: "पत्ते की फोटो लें या अपलोड करें। हमारा AI रोगों की पहचान करता है।",
    readyToScan: "स्कैन के लिए तैयार?",
    dropImage: "छवि डालें या ब्राउज़ करने के लिए क्लिक करें",
    analyzeInfection: "संक्रमण का विश्लेषण करें",
    computing: "रोगों की गणना हो रही है...",
    recommendedRecovery: "अनुशंसित उपचार",
    biologicalMeasures: "जैविक उपाय",
    saveToCloud: "रिपोर्ट क्लाउड पर सहेजें",
    today: 'आज',
    delete: 'मिटाएं',
    state: 'राज्य',
    confirmDelete: 'क्या आप वाकई इस पोस्ट को हटाना चाहते हैं?',
    mandiTitle: "लाइव मंडी भाव",
    mandiSubtitle: "भारत भर में अपनी फसलों के लिए वास्तविक समय के बाजार भावों को ट्रैक करें।",
    cropName: "फसल का नाम",
    market: "बाजार",
    price: "भाव (₹/क्विंटल)",
    trend: "रुझान",
    schemesTitle: "सरकारी योजनाएं",
    schemesSubtitle: "किसानों के लिए उपलब्ध वित्तीय सहायता और सब्सिडी।",
    applyNow: "अभी आवेदन करें",
    details: "विवरण देखें",
    close: "बंद करें",
    aboutScheme: "योजना के बारे में",
    reqDocs: "आवश्यक दस्तावेज",
    communityTitle: "किसान समुदाय",
    communitySubtitle: "साथी किसानों के साथ चर्चा करें, साझा करें और सीखें।",
    newPost: "चर्चा शुरू करें",
    replies: "जवाब",
    welcomeBack: "वापसी पर स्वागत है",
    createAccount: "खाता बनाएं",
    secureLogin: "सुरक्षित कृषि विश्लेषण तक पहुंचें",
    googleLogin: "गूगल के साथ जारी रखें",
    useEmail: "या ईमेल का उपयोग करें",
    email: "ईमेल",
    password: "पास्वर्ड",
    signIn: "साइन इन करें",
    joinNow: "अभी जुड़ें",
    needAccount: "खाता चाहिए? नया पंजीकरण",
    existingMember: "पुरानी सदस्य? सुरक्षित लॉगिन",
    goodMorning: "सुप्रभात",
    goodAfternoon: "नमस्ते",
    goodEvening: "शुभ संध्या",
    dashboardSubtitle: "आज आपकी फसलों का हाल यहाँ है।",
    overallHealth: "कुल फसल स्वास्थ्य",
    activeAlerts: "सक्रिय अलर्ट",
    tasksCompleted: "पूरे किए गए कार्य",
    performanceIndex: "प्रदर्शन सूचंक",
    localWeather: "स्थानीय मौसम",
    detailedForecast: "विस्तृत पूर्वानुमान देखें",
    detectionHistory: "जांच इतिहास",
    liveMarket: "लाइव बाजार भाव",
    updated: "अपडेट किया गया",
    selectState: "राज्य चुनें",
    searchMandi: "बाजार/फसल खोजें...",
    minPrice: "न्यूनतम भाव",
    maxPrice: "अधिकतम भाव",
    modalPrice: "औसत भाव",
    searchCity: "शहर खोजें...",
    humidity: "नमी",
    windSpeed: "हवा की गति",
    precipitation: "वर्षा",
    filterPlaceholder: "फसल या बीमारी खोजें...",
    all: "सभी",
    healthy: "स्वस्थ",
    issues: "समस्याएं मिलीं",
    highSeverity: "गंभीर समस्या",
    attemptDelete: "हटाने का प्रयास:",
    deleteSuccess: "रिकॉर्ड सफलतापूर्वक हटा दिया गया!",
    deleteFail: "हटाने में विफल...",
    confidence: "निश्चितता",
    newDiscussion: "नई चर्चा",
    shareTip: "अपना कृषि प्रश्न या टिप साझा करें...",
    cancel: "रद्द करें",
    post: "पोस्ट करें",
    regionalGroups: "क्षेत्रीय समूह",
    regionalSubtitle: "अपनी स्थानीय भाषा में किसानों से जुड़ें",
    applyWebsite: "आधिकारिक वेबसाइट पर आवेदन करें",
    howItWorks: "यह कैसे काम करता है",
    singleSubject: "एकल विषय",
    singleSubjectDesc: "सुनिश्चित करें कि पत्ता मुख्य फोकस है।",
    naturalLight: "प्राकृतिक प्रकाश",
    naturalLightDesc: "सर्वोत्तम परिणामों के लिए अच्छी रोशनी का प्रयोग करें।",
    highContext: "उच्च संदर्भ",
    highContextDesc: "आसपास के पर्याप्त विवरण कैप्चर करें।",


    // Result Translations (Hindi)
    "Healthy": "स्वस्थ",
    "High": "उच्च",
    "Medium": "मध्यम",
    "Low": "कम",
    "None": "कोई नहीं",
    "General Plant": "सामान्य पौधा",
    "Multiple Crops": "विभिन्न फसलें",
    "Beans / General": "बीन्स / सामान्य",
    "Tomato / Potato / Cotton": "टमाटर / आलू / कपास",
    "Corn / Wheat": "मक्का / गेहूं",
    "General": "सामान्य",
    "Tomato / Wheat": "टमाटर / गेहूं",
    "Berries / Beans": "बेरीज / बीन्स",
    "Tomato": "टमाटर",
    "Potato": "आलू",
    "CropAdvisory": "फसल सलाह",
    "organicSolutions": "जैविक उपाय",
    "healthyMessageTitle": "बढ़िया खबर! आपका पौधा स्वस्थ है।",
    "healthyMessageBody": "सर्वोत्तम परिणामों के लिए नियमित निगरानी और देखभाल जारी रखें।",
    "Powdery Mildew": "पाउडरी मिल्ड्यू (फफूंदी)",
    "Bacterial Blight": "बैक्टीरियल ब्लाइट",
    "Verticillium Wilt": "वर्टिसिलियम विल्ट",
    "Leaf Rust": "लीफ रस्ट (जंग)",
    "Viral Mosaic / Chlorosis": "वायरल मोज़ेक / क्लोरोसिस",
    "Septoria Leaf Spot": "सेप्टोरिया लीफ स्पॉट",
    "Anthracnose (Bird's Eye Spot)": "एन्थ्रेक्नोज",
    "Tomato Leaf Mold": "टमाटर का लीफ मोल्ड",
    "Not a Crop": "फसल नहीं है",
    "Potato Late Blight": "आलू की पछेती झुलसा",

    schemesData: [
        { title: 'पीएम-किसान सम्मान निधि', provider: 'केंद्र सरकार', benefit: '₹6,000/वर्ष', eligibility: 'छोटे/सीमांत किसान', link: 'https://pmkisan.gov.in/', details: 'सभी पात्र किसान परिवारों को ₹6,000 प्रति वर्ष का आय समर्थन।', docs: ['आधार कार्ड', 'भूमि रिकॉर्ड', 'बैंक खाता'] },
        { title: 'पीएम फसल बीमा योजना', provider: 'केंद्र सरकार', benefit: 'फसल बीमा', eligibility: 'KCC धारक', link: 'https://pmfby.gov.in/', details: 'प्राकृतिक आपदाओं से फसल नुकसान पर व्यापक बीमा सुरक्षा।', docs: ['बुवाई प्रमाण पत्र', 'भूमि रिकॉर्ड', 'ID प्रमाण'] },
        { title: 'किसान क्रेडिट कार्ड (KCC)', provider: 'स्टेट बैंक', benefit: 'कम ब्याज ऋण', eligibility: 'पात्र किसान', link: 'https://www.myscheme.gov.in/schemes/kcc', details: 'कम ब्याज दर पर खेती के लिए समय पर ऋण उपलब्ध कराना।', docs: ['आवेदन पत्र', 'भूमि दस्तावेज', 'पासपोर्ट फोटो'] },
        { title: 'कुसुम योजना', provider: 'MNRE', benefit: 'सोलर पंप सब्सिडी', eligibility: 'व्यक्तिगत किसान', link: 'https://pmkusum.mnre.gov.in/', details: 'सौर पंप लगाने के लिए भारी सब्सिडी। बिजली की बचत।', docs: ['सोलर पंप आवेदन', 'पहचान प्रमाण', 'भूमि के कागजात'] },
        { title: 'एग्री-इंफ्रास्ट्रक्चर फंड', provider: 'केंद्र सरकार', benefit: 'भंडारण सब्सिडी', eligibility: 'स्टार्टअप और किसान', link: 'https://theagriculturefund.nic.in/', details: 'फसल कटाई के बाद गोदाम और कोल्ड स्टोरेज बनाने के लिए ऋण।', docs: ['DPR', 'KYC दस्तावेज', 'बैंक ऋण स्वीकृति'] },
        { title: 'पीएम किसान मानधन योजना', provider: 'केंद्र सरकार', benefit: '₹3,000/माह पेंशन', eligibility: 'छोटे किसान (18-40 वर्ष)', link: 'https://maandhan.in/', details: '60 वर्ष की आयु के बाद ₹3,000 प्रति माह पेंशन।', docs: ['आधार कार्ड', 'बचत बैंक खाता'] },
        { title: 'डिजिटल कृषि मिशन', provider: 'कृषि मंत्रालय', benefit: 'डिजिटल सेवाएं', eligibility: 'सभी किसान', link: 'https://agriwelfare.gov.in/', details: 'मिट्टी की जानकारी, बाजार भाव और मौसम के लिए डिजिटल सुविधाएं।', docs: ['आधार कार्ड', 'मोबाइल नंबर'] },
        { title: 'क्लीन प्लांट प्रोग्राम', provider: 'बागवानी बोर्ड', benefit: 'रोग मुक्त पौधे', eligibility: 'बागवानी किसान', link: 'https://www.nhb.gov.in/', details: 'उच्च गुणवत्ता वाले रोग-मुक्त पौधे उपलब्ध कराने की पहल।', docs: ['भूमि रिकॉर्ड', 'किसान पंजीकरण'] },
    ],
    // Hindi Dynamic
    "Paddy (Dhan)": "धान (चावल)",
    "Wheat": "गेहूं",
    "Cotton": "कपास",
    "Maize": "मक्का",
    "Onion": "प्याज",
    "Chilli": "मिर्च",
    "Turmeric": "हल्दी",
    "Groundnut": "मूंगफली",
    "Soybean": "सोयाबीन",
    "Mustard": "सरसों",
    "Andhra Pradesh": "आंध्र प्रदेश",
    "Telangana": "तेलंगाना",
    "Karnataka": "कर्नाटक",
    "Maharashtra": "महाराष्ट्र",
    "Punjab": "पंजाब",
    "Uttar Pradesh": "उत्तर प्रदेश",
    "Madhya Pradesh": "मध्य प्रदेश",
    "Tamil Nadu": "तमिलनाडु",
    "Gujarat": "गुजरात",
    "Haryana": "हरियाणा",
    noCropDetected: "कोई फसल नहीं मिली",
    noCropDetectedDesc: "यह प्रणाली केवल कृषि फसलों का विश्लेषण करती है। कृपया फसल के पत्ते या तने की स्पष्ट तस्वीर अपलोड करें।",
    tryAnotherImage: "दूसरी छवि स्कैन करें",
    severity: "गंभीरता",
    "Hydrogen dioxide": "हाइड्रोजन डाइऑक्साइड",
    "Mancozeb": "मानकोजेब (Mancozeb)",
    "Continue regular monitoring": "नियमित निगरानी जारी रखें",
    "Maintain proper irrigation": "उचित सिंचाई बनाए रखें",
    "Apply balanced fertilizers": "संतुलित उर्वरक डालें",
    "Select resistant varieties": "प्रतिरोधी किस्में चुनें",
    "Improve air circulation": "हवा का संचार सुधारें",
    "Avoid overhead watering": "ऊपर से पानी डालने से बचें",
    "Remove infected plant debris": "संक्रमित पौधों के मलबे को हटा दें",
    "Milk spray (1:10 ratio)": "दूध का छिड़काव (1:10 अनुपात)",
    "Baking soda solution": "बेकिंग सोडा का घोल",
    "Neem oil": "नीम का तेल",
    "Copper-based bactericides (preventative)": "कॉपर-आधारित जीवाणुनाशक (निवारक)",
    "Streptomycin (limited use)": "स्ट्रैप्टोमाइसिन (सीमित उपयोग)",
    "Use disease-free seeds": "रोग मुक्त बीजों का प्रयोग करें",
    "Practice crop rotation": "फसल चक्र अपनाएं",
    "Avoid working in wet fields": "गीले खेतों में काम करने से बचें",
    "Disinfect tools regularly": "औजारों को नियमित रूप से कीटाणुरहित करें",
    "Copper soap": "कॉपर साबुन",
    "Biological controls (Bacillus subtilis)": "जैविक नियंत्रण (बैसिलस सबटिलिस)",
    "Remove infected leaves immediately": "संक्रमित पत्तियों को तुरंत हटा दें",
    "Slow recovery potential - chemicals limited": "उपचार क्षमता धीमी - रसायन सीमित हैं",
    "Soil solarization": "मृदा सौरीकरण (Soil solarization)",
    "Long-term crop rotation (3-4 years)": "दीर्घकालिक फसल चक्र (3-4 वर्ष)",
    "Plant resistant varieties": "रोग प्रतिरोधी किस्में लगाएं",
    "Control nematode populations": "नेमाटोड आबादी को नियंत्रित करें",
    "Soil amendments with compost": "खाद के साथ मिट्टी में सुधार करें",
    "Bio-fungicides (Trichoderma)": "जैविक कवकनाशी (ट्राइकोडेर्मा)",
    "Remove and destroy entire infected plants": "संक्रमित पौधों को पूरी तरह हटा दें और नष्ट कर दें",
    "Azoxystrobin": "एज़ोक्सीस्ट्रोबिन",
    "Propiconazole": "प्रोपिकोनाज़ोल",
    "Plant resistant hybrids": "प्रतिरोधी हाइब्रिड लगाएं",
    "Monitor nutrient levels (avoid excess N)": "पोषक तत्वों के स्तर की निगरानी करें",
    "Apply fungicides at early signs": "शुरुआती लक्षणों पर कवकनाशी लगाएं",
    "Sulfur dust": "सल्फर डस्ट",
    "Remove alternate hosts/weeds": "वैकल्पिक मेजबानों/खरपतवारों को हटा दें",
    "Control insect vectors (aphids/thrips)": "कीट वाहकों को नियंत्रित करें (एफिड्स/थ्रिप्स)",
    "No direct chemical cure for virus": "वायरस के लिए कोई सीधा रासायनिक इलाज नहीं है",
    "Use virus-free certified seeds": "वायरस मुक्त प्रमाणित बीजों का उपयोग करें",
    "Control weeds": "खरपतवारों को नियंत्रित करें",
    "Disinfect tools": "औजारों को कीटाणुरहित करें",
    "Remove infected plants immediately (roguing)": "संक्रमित पौधों को तुरंत हटा दें",
    "Neem oil to repel vectors": "कीटों को दूर भगाने के लिए नीम का तेल",
    "Reflective mulches": "परावर्तक मल्च",
    "Milk spray to prevent mechanical transmission": "यांत्रिक संचरण रोकने के लिए दूध का छिड़काव",
    "Chlorothalonil": "क्लोरोथालोनिल",
    "Copper fungicides": "कॉपर कवकनाशी",
    "Mulching to prevent soil splash": "मिट्टी के छींटों को रोकने के लिए मल्चिंग",
    "Water at base of plant": "पौधे के आधार पर पानी दें",
    "Remove lower leaves": "नीचे की पत्तियां हटा दें",
    "Copper spray": "कॉपर स्प्रे",
    "Biological fungicides": "जैविक कवकनाशी",
    "Enhanced air circulation": "बेहतर वायु संचार",
    "Captan": "कैप्टन",
    "Benomyl": "बेनोमिल",
    "Proper drainage": "उचित जल निकासी",
    "Remove infected fruit/twigs": "संक्रमित फल/टहनियां हटा दें",
    "Hot water seed treatment": "गर्म पानी से बीज उपचार",
    "Chlorothalonil (Daconil)": "क्लोरोथालोनिल (डकॉनिल)",
    "Copper-based fungicide (Bordeaux mixture)": "कॉपर आधारित कवकनाशी (बोर्डो मिश्रण)",
    "Improve air circulation (pruning)": "छंटाई द्वारा वायु संचार सुधारें",
    "Water at roots": "जड़ों में पानी दें",
    "Clean greenhouse structures": "ग्रीनहाउस संरचनाओं को साफ करें",
    "Neem oil spray": "नीम के तेल का छिड़काव",
    "Compost tea": "कम्पोस्ट चाय",
    "Ridomil Gold": "रिडोमिल गोल्ड",
    "Destroy culled potatoes": "छंटे हुए आलू नष्ट कर दें",
    "Plant certified seed": "प्रमाणित बीज लगाएं",
    "Monitor weather (cool/wet favors blight)": "मौसम की निगरानी करें",
    "Kill vines before harvest": "कटाई से पहले बेलों को नष्ट कर दें",
    "Copper products": "कॉपर उत्पाद",
    "Please upload a clear image of a crop leaf": "कृपया फसल के पत्ते की स्पष्ट तस्वीर अपलोड करें",
    "Ensure the image is well-lit": "सुनिश्चित करें कि तस्वीर अच्छी रोशनी में हो",
    "Focus on the plant tissue": "पौधे के ऊतकों पर ध्यान केंद्रित करें"
};

// 3. Define Other Regional Languages

const te = {
    detect: "వ్యాధి నిర్ధారణ",
    dashboard: "డ్యాష్‌బోర్డ్",
    history: "చరిత్ర",
    weather: "వాతావరణం",
    mandi: "మార్కెట్ ధరలు",
    schemes: "పథకాలు",
    community: "రైతు వేదిక",
    login: "ఏజెంట్ లాగిన్",
    logout: "లాగ్ అవుట్",
    fertilizerCalc: "ఎరువుల క్యాలిక్యులేటర్",
    financialTracker: "లాభాల ట్రాకర్",
    agriShops: "వ్యవసాయ దుకాణాలు",
    verified: "ధృవీకరించబడింది",
    distance: "దూరం",
    nearbyShops: "దగ్గరిలోని అధీకృత వ్యవసాయ దుకాణాలు",
    browseProducts: "ఉత్పత్తులను చూడండి",
    alerts: "వ్యాధి హెచ్చరికలు",
    plotSize: "పొలం పరిమాణం",
    acre: "ఎకరా",
    calculate: "లెక్కించు",
    urea: "యూరియా",
    dap: "డి.ఏ.పి (DAP)",
    mop: "ఎం.ఓ.పి (MOP)",
    totalRequirement: "మొత్తం అవసరం",
    initialInvestment: "ప్రారంభ పెట్టుబడి",
    salePrice: "అంచనా విక్రయ ధర",
    otherExpenses: "ఇతర ఖర్చులు",
    profit: "లాభం",
    loss: "నష్టం",
    estimatedNetProfit: "అంచనా నికర లాభం",
    welcome: "మీ పంటలకు నిపుణుల రక్షణ",
    homeSubtitle: "వ్యాధులను గుర్తించండి, చికిత్స పొందండి మరియు నిమిషాల్లో నిపుణులను సంప్రదించండి.",
    startDiagnosis: "పరీక్ష ప్రారంభించండి",
    viewWeather: "వాతావరణం చూడండి",
    trustedBy: "20,000+ రైతుల నమ్మకం",
    accuracy: "98% కచ్చితత్వం",
    instantReport: "తక్షణ నివేదిక",
    expertHelp: "నిపుణుల సహాయం",
    aiCropDoctor: "AI పంట డాక్టర్",
    detectionSubtitle: "ఆకు ఫోటో తీయండి లేదా అప్‌లోడ్ చేయండి. మా AI వ్యాధులను గుర్తిస్తుంది.",
    readyToScan: "స్కాన్ చేయడానికి సిద్ధమా?",
    dropImage: "ఫోటోను ఇక్కడ వదలండి లేదా బ్రౌజ్ చేయండి",
    analyzeInfection: "వ్యాధిని విశ్లేషించండి",
    computing: "వ్యాధులను లెక్కిస్తోంది...",
    recommendedRecovery: "సూచించిన చికిత్స",
    biologicalMeasures: "సేంద్రీయ నివారణలు",
    saveToCloud: "నివేదికను భద్రపరచండి",
    today: 'ఈ రోజు',
    delete: 'తొలగించు',
    state: 'రాష్ట్రం',
    confirmDelete: 'మీరు ఖచ్చితంగా ఈ పోస్ట్‌ను తొలగించాలనుకుంటున్నారా?',
    mandiTitle: "తాజా మార్కెట్ ధరలు",
    mandiSubtitle: "భారతదేశం అంతటా మీ పంటల కోసం నిజ-సమయ మార్కెట్ ధరలను ట్రాక్ చేయండి.",
    cropName: "పంట పేరు",
    market: "మార్కెట్",
    price: "ధర (₹/క్వింటాల్)",
    trend: "సరళి",
    schemesTitle: "ప్రభుత్వ పథకాలు",
    schemesSubtitle: "రైతులకు అందుబాటులో ఉన్న ఆర్థిక సహాయం మరియు రాయితీలు.",
    applyNow: "దరఖాస్తు చేయండి",
    details: "వివరాలు",
    close: "మూసివేయు",
    aboutScheme: "పథకం గురించి",
    reqDocs: "కావలసిన పత్రాలు",
    communityTitle: "రైతు సంఘం",
    communitySubtitle: "తోటి రైతులతో చర్చించండి మరియు నేర్చుకోండి.",
    newPost: "చర్చను ప్రారంభించండి",
    replies: "సమాధానాలు",
    welcomeBack: "స్వాగతం",
    createAccount: "ఖాతా సృష్టించండి",
    secureLogin: "సురక్షిత వ్యవసాయ విశ్లేషణలు",
    googleLogin: "Googleతో కొనసాగండి",
    useEmail: "ఇమెయిల్ ఉపయోగించండి",
    email: "ఇమెయిల్",
    password: "పాస్‌వర్డ్",
    signIn: "సైన్ ఇన్",
    joinNow: "చేరండి",
    needAccount: "ఖాతా కావాలా?",
    existingMember: "లాగిన్ చేయండి",
    goodMorning: "శుభోదయం",
    goodAfternoon: "శుభ మధ్యాహ్నం",
    goodEvening: "శుభ సాయంత్రం",
    dashboardSubtitle: "ఈ రోజు మీ పంటల పరిస్థితి ఇక్కడ ఉంది.",
    overallHealth: "పంట ఆరోగ్యం",
    activeAlerts: "హెచ్చరికలు",
    tasksCompleted: "పూర్తయిన పనులు",
    performanceIndex: "పనితీరు",
    localWeather: "స్థానిక వాతావరణం",
    detailedForecast: "పూర్తి వివరాలు",
    detectionHistory: "పరీక్షల చరిత్ర",
    liveMarket: "తాజా ధరలు",
    updated: "నవీకరించబడింది",
    selectState: "రాష్ట్రాన్ని ఎంచుకోండి",
    searchMandi: "మార్కెట్/పంటను వెతకండి...",
    minPrice: "కనీస ధర",
    maxPrice: "గరిష్ట ధర",
    modalPrice: "సగటు ధర",
    searchCity: "నగరాన్ని వెతకండి...",
    humidity: "తేమ",
    windSpeed: "గాలి వేగం",
    precipitation: "వర్షపాతం",
    filterPlaceholder: "వెతకండి...",
    all: "అన్నీ",
    healthy: "ఆరోగ్యకరమైనవి",
    issues: "సమస్యలు",
    highSeverity: "తీవ్రమైనవి",
    loadingDiscussions: "లోడ్ అవుతోంది...",
    noDiscussions: "చర్చలు లేవు.",
    loadingRecords: "లోడ్ అవుతోంది...",
    noRecords: "డేటా లేదు",
    exportPDF: "PDF ఎగుమతి",
    confidence: "నమ్మకం",
    cloudSynced: "భద్రపరచబడింది",
    unknown: "తెలియదు",
    applyWebsite: "వెబ్‌సైట్‌లో దరఖాస్తు చేయండి",
    deleteSuccess: "తొలగించబడింది!",
    deleteFail: "విఫలమైంది...",
    newDiscussion: "కొత్త చర్చ",
    shareTip: "మీ ప్రశ్నను పంచుకోండి...",
    cancel: "రద్దు",
    post: "పోస్ట్",
    regionalGroups: "ప్రాంతీయ సమూహాలు",
    regionalSubtitle: "మీ భాషలో మాట్లాడండి",
    howItWorks: "ఇది ఎలా పనిచేస్తుంది",
    singleSubject: "ఒకే అంశం",
    singleSubjectDesc: "ఆకు ప్రధాన కేంద్రంగా ఉండేలా చూసుకోండి.",
    naturalLight: "సహజ కాంతి",
    naturalLightDesc: "ఉత్తమ ఫలితాల కోసం మంచి లైటింగ్ ఉపయోగించండి.",
    highContext: "అధిక సందర్భం",
    highContextDesc: "తగినంత చుట్టుపక్కల వివరాలను క్యాప్చర్ చేయండి.",

    // Result Translations (Telugu)
    "Healthy": "ఆరోగ్యంగా ఉంది",
    "High": "తీవ్రమైన",
    "Medium": "మధ్యస్థ",
    "Low": "తక్కువ",
    "None": "ఏమీ లేదు",
    "General Plant": "సాధారణ మొక్క",
    "Multiple Crops": "వివిధ పంటలు",
    "Beans / General": "బీన్స్ / సాధారణ",
    "Tomato / Potato / Cotton": "టమాటా / బంగాళాదుంప / పత్తి",
    "Corn / Wheat": "మొక్కజొన్న / గోధుమ",
    "General": "సాధారణ",
    "Tomato / Wheat": "టమాటా / గోధుమ",
    "Berries / Beans": "బెర్రీలు / బీన్స్",
    "Tomato": "టమాటా",
    "Potato": "బంగాళాదుంప",
    "CropAdvisory": "పంట సలహా",
    "organicSolutions": "సేంద్రీయ పరిష్కారాలు",
    "healthyMessageTitle": "శుభవార్త! మీ మొక్క ఆరోగ్యంగా ఉంది.",
    "healthyMessageBody": "ఉత్తమ ఫలితాల కోసం క్రమం తప్పకుండా పర్యవేక్షించండి.",
    "Powdery Mildew": "బూజు తెగులు",
    "Bacterial Blight": "బాక్టీరియల్ బ్లైట్",
    "Verticillium Wilt": "ఎండు తెగులు",
    "Leaf Rust": "తుప్పు తెగులు",
    "Viral Mosaic / Chlorosis": "వైరల్ మొజాయిక్ / క్లోరోసిస్",
    "Septoria Leaf Spot": "సెప్టోరియా ఆకు మచ్చ",
    "Anthracnose (Bird's Eye Spot)": "ఆంత్రాక్నోస్",
    "Tomato Leaf Mold": "టమాటా ఆకు బూజు",
    "Potato Late Blight": "బంగాళాదుంప లేట్ బ్లైట్",
    "Not a Crop": "పంట కాదు",

    schemesData: [
        { title: 'PM- కిసాన్ సమ్మాన్ నిధి', provider: 'కేంద్ర ప్రభుత్వం', benefit: '₹6,000/ఏడాదికి', eligibility: 'చిన్న రైతులు', link: 'https://pmkisan.gov.in/', details: 'రైతు కుటుంబాలకు సంవత్సరానికి ₹6,000 ఆర్థిక సహాయం.', docs: ['ఆధార్ కార్డు', 'భూమి పత్రాలు', 'బ్యాంకు ఖాతా'] },
        { title: 'PM ఫసల్ బీమా యోజన', provider: 'కేంద్ర ప్రభుత్వం', benefit: 'పంట బీమా', eligibility: 'KCC రైతులు', link: 'https://pmfby.gov.in/', details: 'ప్రకృతి వైపరీత్యాల నుండి పంట నష్టానికి బీమా.', docs: ['పంట సాగు పత్రం', 'భూమి రికార్డులు', 'ID ప్రూఫ్'] },
        { title: 'కిసాన్ క్రెడిట్ కార్డు', provider: 'SBI', benefit: 'తక్కువ వడ్డీ రుణాలు', eligibility: 'అర్హులైన రైతులు', link: 'https://www.myscheme.gov.in/schemes/kcc', details: 'వ్యవసాయ అవసరాలకు తక్కువ వడ్డీపై రుణం.', docs: ['దరఖాస్తు ఫారం', 'భూమి పత్రాలు', 'పాస్‌పోర్ట్ ఫోటో'] },
        { title: 'కుసుమ్ పథకం', provider: 'MNRE', benefit: 'సోలార్ పంపు सब्सिडी', eligibility: 'రైతులు', link: 'https://pmkusum.mnre.gov.in/', details: 'సౌర విద్యుత్ పంపుల ఏర్పాటుకు రాయితీలు.', docs: ['దరఖాస్తు', 'గుర్తింపు కార్డు', 'భూమి పత్రాలు'] },
        { title: 'అగ్రి-ఇన్‌ఫ్రా ఫండ్', provider: 'కేంద్ర ప్రభుత్వం', benefit: 'గోదాము రాయితీ', eligibility: 'రైతులు', link: 'https://theagriculturefund.nic.in/', details: 'నిల్వ మరియు మౌలిక సదుపాయాల కోసం రుణం.', docs: ['ప్రాజెక్ట్ రిపోర్ట్', 'KYC', 'బ్యాంకు ఆమోదం'] },
        { title: 'PM కిసాన్ మాన్‌ధన్ యోజన', provider: 'కేంద్ర ప్రభుత్వం', benefit: '₹3,000/నెల పెన్షన్', eligibility: 'చిన్న రైతులు (18-40 ఏళ్లు)', link: 'https://maandhan.in/', details: '60 ఏళ్ళు నిండిన రైతులకు ₹3,000 నెలవారీ పెన్షన్.', docs: ['ఆధార్ కార్డు', 'బ్యాంకు ఖాతా'] },
        { title: 'డిజిటల్ వ్యవసాయ మిషన్', provider: 'వ్యవసాయ శాఖ', benefit: 'డిజిటల్ సేవలు', eligibility: 'అందరూ రైతులు', link: 'https://agriwelfare.gov.in/', details: 'రైతులకు డిజిటల్ సేవలు మరియు మార్కెట్ సమాచారం.', docs: ['ఆధార్ కార్డు', 'మొబైల్ నంబర్'] },
        { title: 'క్లీన్ ప్లాంట్ ప్రోగ్రామ్', provider: 'హార్టికల్చర్ బోర్డ్', benefit: 'రోగరహిత మొక్కలు', eligibility: 'వ్యాపార రైతులు', link: 'https://www.nhb.gov.in/', details: 'అధిక విలువ కలిగిన పంటలకు నాణ్యమైన మొక్కలు.', docs: ['భూమి రికార్డులు', 'రిజిస్ట్రేషన్ ID'] },
    ],
    // Telugu Dynamic
    "Paddy (Dhan)": "వరి (ధాన్యం)",
    "Wheat": "గోధుమలు",
    "Cotton": "పత్తి",
    "Maize": "మొక్కజొన్న",
    "Onion": "ఉల్లిపాయలు",
    "Chilli": "మిరపకాయలు",
    "Turmeric": "పసుపు",
    "Groundnut": "వేరుశెనగ",
    "Soybean": "సోయాబీన్",
    "Mustard": "ఆవాలు",
    "Andhra Pradesh": "ఆంధ్రప్రదేశ్",
    "Telangana": "తెలంగాణ",
    "Karnataka": "కర్ణాటక",
    "Maharashtra": "మహారాష్ట్ర",
    "Punjab": "పంజాబ్",
    "Uttar Pradesh": "ఉత్తర ప్రదేశ్",
    "Madhya Pradesh": "మధ్య ప్రదేశ్",
    "Tamil Nadu": "తమిళనాడు",
    "Gujarat": "గుజరాత్",
    "Haryana": "హర్యానా",
    noCropDetected: "పంటను గుర్తించలేదు",
    noCropDetectedDesc: "ఈ వ్యవస్థ పంటలను మాత్రమే విశ్లేషిస్తుంది. దయచేసి పంట ఆకు లేదా కాండం యొక్క స్పష్టమైన ఫోటోను అప్‌లోడ్ చేయండి.",
    tryAnotherImage: "మరో చిత్రాన్ని ప్రయత్నించండి",
    severity: "తీవ్రత",
    "Copper-based bactericides (preventative)": "రాగి ఆధారిత బాక్టీరిసైడ్లు (నివారణ)",
    "Streptomycin (limited use)": "స్ట్రెప్టోమైసిన్ (పరిమిత వినియోగం)",
    "Use disease-free seeds": "వ్యాధి రహిత విత్తనాలను ఉపయోగించండి",
    "Practice crop rotation": "పంట మార్పిడిని ప్రాక్టీస్ చేయండి",
    "Avoid working in wet fields": "తడి పొలాల్లో పనిచేయడం మానుకోండి",
    "Disinfect tools regularly": "సామగ్రిని క్రమం తప్పకుండా శుభ్రపరచండి",
    "Copper soap": "రాగి సబ్బు (Copper soap)",
    "Biological controls (Bacillus subtilis)": "జీవ నియంత్రణలు (బాసిల్లస్ సబ్టిలిస్)",
    "Remove infected leaves immediately": "సోకిన ఆకులను వెంటనే తొలగించండి",
    "Sulfur-based fungicides": "సల్ఫర్ ఆధారిత శిలీంద్ర సంహారిణులు",
    "Neem oil": "వేప నూనె",
    "Mancozeb": "మాంకోజెబ్ (Mancozeb)",
    "Water at roots": "వేర్ల వద్ద నీరు పోయండి",
    "Improve air circulation": "గాలి ప్రసరణను మెరుగుపరచండి",
    "Slow recovery potential - chemicals limited": "కోలుకునే అవకాశం తక్కువ - రసాయనాలు పరిమితం",
    "Soil solarization": "నేల సూర్యరశ్మి చికిత్స (Soil solarization)",
    "Long-term crop rotation (3-4 years)": "దీర్ఘకాలిక పంట మార్పిడి (3-4 సంవత్సరాలు)",
    "Plant resistant varieties": "వ్యాధి నిరోధక రకాలను నాటండి",
    "Control nematode populations": "నెమటోడ్ జనాభాను నియంత్రించండి",
    "Soil amendments with compost": "కంపోస్ట్‌తో నేలను మెరుగుపరచండి",
    "Bio-fungicides (Trichoderma)": "జీవ శిలీంద్ర సంహారిణులు (ట్రైకోడెర్మా)",
    "Remove and destroy entire infected plants": "వ్యాధి సోకిన మొక్కలను పూర్తిగా తొలగించి నాశనం చేయండి",
    "Potassium bicarbonate": "పొటాషియం బైకార్బోనేట్",
    "Myclobutanil": "మైక్లోబుటానిల్",
    "Select resistant varieties": "నిరోధక రకాలను ఎంచుకోండి",
    "Avoid overhead watering": "పై నుండి నీరు పోయడం మానుకోండి",
    "Remove infected plant debris": "సోకిన మొక్కల వ్యర్థాలను తొలగించండి",
    "Milk spray (1:10 ratio)": "పాలు స్ప్రే (1:10 నిష్పత్తి)",
    "Baking soda solution": "బేకింగ్ సోడా ద్రావణం",
    "Azoxystrobin": "అజోక్సిస్ట్రోబిన్",
    "Propiconazole": "ప్రోపికోనాజోల్",
    "Plant resistant hybrids": "నిరోధక హైబ్రిడ్లను నాటండి",
    "Monitor nutrient levels (avoid excess N)": "పోషక స్థాయిలను పర్యవేక్షించండి",
    "Apply fungicides at early signs": "ప్రారంభ దశలోనే శిలీంద్ర సంహారిణులను వాడండి",
    "Sulfur dust": "గంధకపు పొడి",
    "Remove alternate hosts/weeds": "ప్రత్యామ్నాయ కలుపు మొక్కలను తొలగించండి",
    "Control insect vectors (aphids/thrips)": "కీటక వాహకాలను నియంత్రించండి (పేనుబంక/తామర పురుగులు)",
    "No direct chemical cure for virus": "వైరస్‌కు ప్రత్యక్ష రసాయన చికిత్స లేదు",
    "Use virus-free certified seeds": "వైరస్ లేని ధృవీకరించబడిన విత్తనాలను వాడండి",
    "Control weeds": "కలుపు మొక్కలను నియంత్రించండి",
    "Remove infected plants immediately (roguing)": "సోకిన మొక్కలను వెంటనే లాగివేయండి",
    "Reflective mulches": "పరావర్తన మల్చ్‌లు",
    "Milk spray to prevent mechanical transmission": "వ్యాప్తిని అరికట్టడానికి పాలు స్ప్రే చేయండి",
    "Chlorothalonil": "క్లోరోథలోనిల్",
    "Copper fungicides": "రాగి శిలీంద్ర సంహారిణులు",
    "Mulching to prevent soil splash": "నేల చిమ్మకుండా మల్చింగ్ చేయండి",
    "Water at base of plant": "మొక్క మొదలు వద్ద నీరు పోయండి",
    "Remove lower leaves": "క్రింది ఆకులను తొలగించండి",
    "Copper spray": "రాగి ద్రావణం స్ప్రే",
    "Biological fungicides": "జీవ శిలీంద్ర సంహారిణులు",
    "Enhanced air circulation": "మెరుగైన గాలి ప్రసరణ",
    "Captan": "కాప్టాన్",
    "Benomyl": "బెనోమిల్",
    "Proper drainage": "సరైన నీటి పారుదల",
    "Remove infected fruit/twigs": "సోకిన పండ్లు/కొమ్మలను తొలగించండి",
    "Hot water seed treatment": "వేడి నీటి విత్తన చికిత్స",
    "Chlorothalonil (Daconil)": "క్లోరోథలోనిల్ (డాకోనిల్)",
    "Copper-based fungicide (Bordeaux mixture)": "రాగి ఆధారిత శిలీంద్ర సంహారిణి (బోర్డో మిశ్రమం)",
    "Improve air circulation (pruning)": "కత్తిరింపు ద్వారా గాలి ప్రసరణ మెరుగుపరచండి",
    "Clean greenhouse structures": "గ్రీన్హౌస్ నిర్మాణాలను శుభ్రం చేయండి",
    "Neem oil spray": "వేప నూనె స్ప్రే",
    "Compost tea": "కంపొస్ట్ టీ",
    "Ridomil Gold": "రిడోమిల్ గోల్డ్",
    "Destroy culled potatoes": "పనికిరాని ఆలుగడ్డలను నాశనం చేయండి",
    "Plant certified seed": "ధృవీకరించబడిన విత్తనాలను నాటండి",
    "Monitor weather (cool/wet favors blight)": "వాతావరణాన్ని పర్యవేక్షించండి",
    "Kill vines before harvest": "పంట కోతకు ముందు తీగలను నరికివేయండి",
    "Copper products": "రాగి ఉత్పత్తులు",
    "Hydrogen dioxide": "హైడ్రోజన్ డయాక్సైడ్",
    "Continue regular monitoring": "క్రమం తప్పకుండా పర్యవేక్షించండి",
    "Maintain proper irrigation": "సరైన నీటి పారుదలని నిర్వహించండి",
    "Apply balanced fertilizers": "సమతుల్య ఎరువులను వాడండి",
    "Disinfect tools": "సామగ్రిని శుభ్రపరచండి",
    "Crop rotation": "పంట మార్పిడి",
    "Please upload a clear image of a crop leaf": "దయచేసి పంట ఆకు యొక్క స్పష్టమైన చిత్రాన్ని అప్‌లోడ్ చేయండి",
    "Ensure the image is well-lit": "చిత్రం తగినంత వెలుతురులో ఉందని నిర్ధారించుకోండి",
    "Focus on the plant tissue": "మొక్క భాగంపై దృష్టి పెట్టండి"
};

const kn = {
    detect: "ರೋಗ ಪತ್ತೆ",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    history: "ಇತಿಹಾಸ",
    weather: "ಹವಾಮಾನ",
    mandi: "ಮಾರುಕಟ್ಟೆ ಬೆಲೆ",
    schemes: "ಯೋಜನೆಗಳು",
    community: "ರೈತ ಸಮುದಾಯ",
    login: "ಏಜೆಂಟ್ ಲಾಗಿನ್",
    logout: "ಲಾಗ್ ಔಟ್",
    fertilizerCalc: "ಗೊಬ್ಬರ ಕ್ಯಾಲ್ಕುಲೇಟರ್",
    financialTracker: "ಲಾಭ ಟ್ರ್ಯಾಕರ್",
    agriShops: "ಕೃಷಿ ಅಂಗಡಿಗಳು",
    verified: "ದೃಢೀಕರಿಸಲ್ಪಟ್ಟಿದೆ",
    distance: "ದೂರ",
    nearbyShops: "ಸಮೀಪದ ದೃಢೀಕೃತ ಕೃಷಿ ಅಂಗಡಿಗಳು",
    browseProducts: "ಉತ್ಪನ್ನಗಳನ್ನು ನೋಡಿ",
    alerts: "ರೋಗದ ಎಚ್ಚರಿಕೆ",
    plotSize: "ಜಮೀನಿನ ವಿಸ್ತೀರ್ಣ",
    acre: "ಎಕರೆ",
    calculate: "ಲೆಕ್ಕಾಚಾರ ಮಾಡಿ",
    urea: "ಯೂರಿಯಾ",
    dap: "ಡಿಎಪಿ",
    mop: "ಎಂಒಪಿ",
    totalRequirement: "ಒಟ್ಟು ಅವಶ್ಯಕತೆ",
    initialInvestment: "ಆರಂಭಿಕ ಹೂಡಿಕೆ",
    salePrice: "ನಿರೀಕ್ಷಿತ ಮಾರಾಟ ಬೆಲೆ",
    otherExpenses: "ಇತರೆ ವೆಚ್ಚಗಳು",
    profit: "ಲಾಭ",
    loss: "ನಷ್ಟ",
    estimatedNetProfit: "ಅಂದಾಜು ನಿವ್ವಳ ಲಾಭ",
    welcome: "ನಿಮ್ಮ ಬೆಳೆಗಳಿಗೆ ತಜ್ಞರ ರಕ್ಷಣೆ",
    homeSubtitle: "ರೋಗಗಳನ್ನು ಗುರುತಿಸಿ ಮತ್ತು ತಜ್ಞರ ಸಲಹೆ ಪಡೆಯಿರಿ.",
    startDiagnosis: "ಪರೀಕ್ಷಿಸಿ",
    viewWeather: "ಹವಾಮಾನ ವರದಿ",
    trustedBy: "20,000+ ರೈತರ ನಂಬಿಕೆ",
    accuracy: "98% ನಿಖರತೆ",
    instantReport: "ತಕ್ಷಣದ ವರದಿ",
    expertHelp: "ತಜ್ಞರ ಸಹಾಯ",
    aiCropDoctor: "AI ಕ್ರಾಪ್ ಡಾಕ್ಟರ್",
    detectionSubtitle: "ಎಲೆಯ ಫೋಟೋ ತೆಗೆಯಿರಿ. ನಮ್ಮ AI ರೋಗವನ್ನು ಪತ್ತೆ ಮಾಡುತ್ತದೆ.",
    readyToScan: "ಸ್ಕ್ಯಾನ್ ಮಾಡಲು ಸಿದ್ಧರಿದ್ದೀರಾ?",
    dropImage: "ಚಿತ್ರವನ್ನು ಇಲ್ಲಿ ಹಾಕಿ",
    analyzeInfection: "ವಿಶ್ಲೇಷಿಸಿ",
    computing: "ಲೆಕ್ಕಾಚಾರ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    recommendedRecovery: "ಶಿಫಾರಸು ಮಾಡಿದ ಚಿಕಿತ್ಸೆ",
    biologicalMeasures: "ಸಾವಯವ ಕ್ರಮಗಳು",
    saveToCloud: "ವರದಿ ಉಳಿಸಿ",
    today: 'ಇಂದು',
    delete: 'ಅಳಿಸಿ',
    state: 'ರಾಜ್ಯ',
    confirmDelete: 'ಈ ಪೋಸ್ಟ್ ಅನ್ನು ಅಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿದ್ದೀರಾ?',
    mandiTitle: "ಮಾರುಕಟ್ಟೆ ದರಗಳು",
    mandiSubtitle: "ಭಾರತದಾದ್ಯಂತ ನಿಮ್ಮ ಬೆಳೆಗಳ ಮಾರುಕಟ್ಟೆ ದರಗಳನ್ನು ತಿಳಿಯಿರಿ.",
    cropName: "ಬೆಳೆ ಹೆಸರು",
    market: "ಮಾರುಕಟ್ಟೆ",
    price: "ಬೆಳೆ (₹/ಕ್ವಿಂಟಾಲ್)",
    trend: "ಒಲವು",
    schemesTitle: "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
    schemesSubtitle: "ರೈತರಿಗೆ ಆರ್ಥಿಕ ಸಹಾಯ ಮತ್ತು ಸಬ್ಸಿಡಿಗಳು.",
    applyNow: "ಅರ್ಜಿ ಹಾಕಿ",
    details: "ವಿವರಗಳು",
    close: "ಮುಚ್ಚಿ",
    aboutScheme: "ಯೋಜನೆಯ ಬಗ್ಗೆ",
    reqDocs: "ಅಗತ್ಯ ದಾಖಲೆಗಳು",
    communityTitle: "ರೈತ ವೇದಿಕೆ",
    communitySubtitle: "ಸಹ ರೈತರೊಂದಿಗೆ ಚರ್ಚಿಸಿ.",
    newPost: "ಚರ್ಚೆ ಪ್ರಾರಂಭಿಸಿ",
    replies: "ಉತ್ತರಗಳು",
    welcomeBack: "ಸ್ವಾಗತ",
    createAccount: "ಖಾತೆ ರಚಿಸಿ",
    secureLogin: "ಸುರಕ್ಷಿತ ಲಾಗಿನ್",
    googleLogin: "Google ಜತೆ ಮುಂದುವರಿಯಿರಿ",
    useEmail: "ಇಮೇಲ್ ಬಳಸಿ",
    email: "ಇಮೇಲ್",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    signIn: "ಸೈನ್ ಇನ್",
    joinNow: "ಸೇರಿಕೊಳ್ಳಿ",
    needAccount: "ಖಾತೆ ಬೇಕೇ?",
    existingMember: "ಲಾಗಿನ್ ಆಗಿ",
    goodMorning: "ಶುಭೋದಯ",
    goodAfternoon: "ಶುಭ ಮಧ್ಯಾಹ್ನ",
    goodEvening: "ಶುಭ ಸಂಜೆ",
    dashboardSubtitle: "ನಿಮ್ಮ ಬೆಳೆಗಳ ಸ್ಥಿತಿ ಇಲ್ಲಿದೆ.",
    overallHealth: "ಬೆಳೆ ಆರೋಗ್ಯ",
    activeAlerts: "ಎಚ್ಚರಿಕೆಗಳು",
    tasksCompleted: "ಪೂರ್ಣಗೊಂಡ ಕಾರ್ಯಗಳು",
    performanceIndex: "ಕಾರ್ಯಕ್ಷಮತೆ",
    localWeather: "ಸ್ಥಳೀಯ ಹವಾಮಾನ",
    detailedForecast: "ಪೂರ್ಣ ವರದಿ",
    detectionHistory: "ಪತ್ತೆ ಇತಿಹಾಸ",
    liveMarket: "ಲೈವ್ ದರಗಳು",
    updated: "ನವೀಕರಿಸಲಾಗಿದೆ",
    selectState: "ರಾಜ್ಯ ಆಯ್ಕೆಮಾಡಿ",
    searchMandi: "ಹುಡುಕಿ...",
    minPrice: "ಕನಿಷ್ಠ ಬೆಲೆ",
    maxPrice: "ಗರಿಷ್ಠ ಬೆಲೆ",
    modalPrice: "ಸರಾಸರಿ ಬೆಲೆ",
    searchCity: "ನಗರ ಹುಡುಕಿ...",
    humidity: "ತೇವಾಂಶ",
    windSpeed: "ಗಾಳಿಯ ವೇಗ",
    precipitation: "ಮಳೆ",
    filterPlaceholder: "ಹುಡುಕಿ...",
    all: "ಎಲ್ಲಾ",
    healthy: "ಆರೋಗ್ಯಕರ",
    issues: "ಸಮಸ್ಯೆಗಳು",
    highSeverity: "ಗಂಭೀರ",
    loadingDiscussions: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    noDiscussions: "ಯಾವುದೇ ಚರ್ಚೆಗಳಿಲ್ಲ.",
    loadingRecords: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    noRecords: "ಮಾಹಿತಿ ಇಲ್ಲ",
    exportPDF: "PDF ಡೌನ್‌ಲೋಡ್",
    confidence: "ನಂಬಿಕೆ",
    cloudSynced: "ಕ್ಲೌಡ್ ಸಿಂಕ್",
    unknown: "ಗೊತ್ತಿಲ್ಲ",
    applyWebsite: "ವೆಬ್‌ಸೈಟ್‌ಗೆ ಭೇಟಿ ನೀಡಿ",
    deleteSuccess: "ಅಳಿಸಲಾಗಿದೆ!",
    deleteFail: "ವಿಫಲವಾಗಿದೆ...",
    newDiscussion: "ಹೊಸ ಚರ್ಚೆ",
    shareTip: "ಪ್ರಶ್ನೆ ಕೇಳಿ...",
    cancel: "ರದ್ದು",
    post: "ಪೋಸ್ಟ್",
    regionalGroups: "ಪ್ರಾದೇಶಿಕ ಗುಂಪುಗಳು",
    regionalSubtitle: "ಸ್ಥಳೀಯ ಭಾಷೆಯಲ್ಲಿ ಮಾತನಾಡಿ",
    howItWorks: "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
    singleSubject: "ಒಂದೇ ವಿಷಯ",
    singleSubjectDesc: "ಎಲೆ ಮುಖ್ಯ ಕೇಂದ್ರಬಿಂದುವಾಗಿದೆ ಎಂದು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ.",
    naturalLight: "ನೈಸರ್ಗಿಕ ಬೆಳಕು",
    naturalLightDesc: "ಉತ್ತಮ ಫಲಿತಾಂಶಗಳಿಗಾಗಿ ಉತ್ತಮ ಬೆಳಕನ್ನು ಬಳಸಿ.",
    highContext: "ಹೆಚ್ಚಿನ ಸಂದರ್ಭ",
    highContextDesc: "ಸಾಕಷ್ಟು ಸುತ್ತಮುತ್ತಲಿನ ವಿವರಗಳನ್ನು ಸೆರೆಹಿಡಿಯಿರಿ.",

    // Result Translations (Kannada)
    "Healthy": "ಆರೋಗ್ಯಕರ",
    "High": "ಹೆಚ್ಚು",
    "Medium": "ಮಧ್ಯಮ",
    "Low": "ಕಡಿಮೆ",
    "None": "ಇಲ್ಲ",
    "General Plant": "ಸಾಮಾನ್ಯ ಸಸ್ಯ",
    "Multiple Crops": "ವಿವಿಧ ಬೆಳೆಗಳು",
    "Beans / General": "ಬೀನ್ಸ್ / ಸಾಮಾನ್ಯ",
    "Tomato / Potato / Cotton": "ಟೊಮ್ಯಾಟೊ / ಆಲೂಗಡ್ಡೆ / ಹತ್ತಿ",
    "Corn / Wheat": "ಜೋಳ / ಗೋಧಿ",
    "General": "ಸಾಮಾನ್ಯ",
    "Tomato / Wheat": "ಟೊಮ್ಯಾಟೊ / ಗೋಧಿ",
    "Berries / Beans": "ಬೆರ್ರಿಗಳು / ಬೀನ್ಸ್",
    "Tomato": "ಟೊಮ್ಯಾಟೊ",
    "Potato": "ಆಲೂಗಡ್ಡೆ",
    "CropAdvisory": "ಬೆಳೆ ಸಲಹೆ",
    "organicSolutions": "ಸಾವಯವ ಪರಿಹಾರಗಳು",
    "healthyMessageTitle": "ಉತ್ತಮ ಸುದ್ದಿ! ನಿಮ್ಮ ಸಸ್ಯ ಆರೋಗ್ಯಕರವಾಗಿದೆ.",
    "healthyMessageBody": "ಉತ್ತಮ ಫಲಿತಾಂಶಗಳಿಗಾಗಿ ನಿಯಮಿತವಾಗಿ ಗಮನವಿರಲಿ.",
    "Powdery Mildew": "ಬೂದಿ ರೋಗ",
    "Bacterial Blight": "ಬ್ಯಾಕ್ಟೀರಿಯಲ್ ಬ್ಲೈಟ್",
    "Verticillium Wilt": "ಒಣಗು ರೋಗ",
    "Leaf Rust": "ಎಲೆ ತುಕ್ಕು ರೋಗ",
    "Viral Mosaic / Chlorosis": "ವೈರಲ್ ಮೊಸಾಯಿಕ್",
    "Septoria Leaf Spot": "ಸೆಪ್ಟೋರಿಯಾ ಎಲೆ ಚುಕ್ಕೆ",
    "Anthracnose (Bird's Eye Spot)": "ಆಂಥ್ರಾಕ್ನೋಸ್",
    "Tomato Leaf Mold": "ಟೊಮ್ಯಾಟೊ ಎಲೆ ಶಿಲೀಂಧ್ರ",
    "Potato Late Blight": "ಆಲೂಗಡ್ಡೆ ಅಂಗಮಾರಿ ರೋಗ",
    "Not a Crop": "ಬೆಳೆ ಅಲ್ಲ",

    schemesData: [
        { title: 'PM- ಕಿಸಾನ್ ಸಮ್ಮಾನ್ ನಿಧಿ', provider: 'ಕೇಂದ್ರ ಸರ್ಕಾರ', benefit: '₹6,000/ವರ್ಷಕ್ಕೆ', eligibility: 'ಸಣ್ಣ ರೈತರು', link: 'https://pmkisan.gov.in/', details: 'ರೈತ ಕುಟುಂಬಗಳಿಗೆ ವಾರ್ಷಿಕ ₹6,000 ಆರ್ಥಿಕ ಬೆಂಬಲ.', docs: ['ಆಧಾರ್ ಕಾರ್ಡ್', 'ಭೂಮಿ ದಾಖಲೆ', 'ಬ್ಯಾಂಕ್ ಖಾತೆ'] },
        { title: 'PM ಫಸಲ್ ಬಿಮಾ ಯೋಜನೆ', provider: 'ಕೇಂದ್ರ ಸರ್ಕಾರ', benefit: 'ಬೆಳೆ ವಿಮೆ', eligibility: 'KCC ಹೊಂದಿರುವವರು', link: 'https://pmfby.gov.in/', details: 'ಪ್ರಕೃತಿ ವಿಕೋಪಗಳಿಂದ ಉಂಟಾಗುವ ಬೆಳೆ ನಷ್ಟಕ್ಕೆ ವಿಮೆ.', docs: ['ಬಿತ್ತನೆ ಪ್ರಮಾಣಪತ್ರ', 'ಭೂಮಿ ದಾಖಲೆ', 'ID ಪುರಾವೆ'] },
        { title: 'ಕಿಸಾನ್ ಕ್ರೆಡಿಟ್ ಕಾರ್ಡ್', provider: 'SBI', benefit: 'ಕಡಿಮೆ ಬಡ್ಡಿ ಸಾಲ', eligibility: 'ಅರ್ಹ ರೈತರು', link: 'https://www.myscheme.gov.in/schemes/kcc', details: 'ಕೃಷಿ ಅಗತ್ಯಗಳಿಗಾಗಿ ಕಡಿಮೆ ಬಡ್ಡಿದರದಲ್ಲಿ ಸಾಲ ಸೌಲಭ್ಯ.', docs: ['ಅರ್ಜಿ', 'ಭೂಮಿ ದಾಖಲೆ', 'ಫೋಟೋ'] },
        { title: 'ಕುಸುಮ್ ಯೋಜನೆ', provider: 'MNRE', benefit: 'ಸೌರ ಪಂಪ್‌ಗಳು', eligibility: 'ರೈತರು', link: 'https://pmkusum.mnre.gov.in/', details: 'ಸೌರ ಕೃಷಿ ಪಂಪ್‌ಗಳ ಅಳವಡಿಕೆಗೆ ಭಾರಿ ಸಹಾಯಧನ.', docs: ['ಅರ್ಜಿ', 'ಗುರುತಿನ ಚೀಟಿ', 'ಭೂಮಿ ದಾಖಲೆ'] },
        { title: 'ಅಗ್ರಿ-ಇನ್ಫ್ರಾ ಫಂಡ್', provider: 'ಕೇಂದ್ರ ಸರ್ಕಾರ', benefit: 'ಗೋದಾಮು ಸಬ್ಸಿಡಿ', eligibility: 'ರೈತರು', link: 'https://theagriculturefund.nic.in/', details: 'ಕೊಯ್ಲು ನಂತರದ ಬೆಳೆ ಶೇಖರಣೆಗಾಗಿ ಸಾಲ ಮತ್ತು ಸಹಾಯಧನ.', docs: ['ಯೋಜನಾ ವರದಿ', 'KYC', 'ಬ್ಯಾಂಕ್ ಅನುಮೋದನೆ'] },
        { title: 'PM ಕಿಸಾನ್ ಮಾನ್ ಧನ್', provider: 'ಕೇಂದ್ರ ಸರ್ಕಾರ', benefit: '₹3,000/ತಿಂಗಳು ಪಿಂಚಣಿ', eligibility: 'ಸಣ್ಣ ರೈತರು (18-40 ವರ್ಷ)', link: 'https://maandhan.in/', details: '60 ವರ್ಷ ವಯಸ್ಸಿನ ನಂತರ ಮಾಸಿಕ ₹3,000 ಪಿಂಚಣಿ.', docs: ['ಆಧಾರ್ ಕಾರ್ಡ್', 'ಬ್ಯಾಂಕ್ ಪಾಸ್ ಪುಸ್ತಕ'] },
        { title: 'ಡಿಜಿಟಲ್ ಕೃಷಿ ಮಿಷನ್', provider: 'ಕೃಷಿ ಇಲಾಖೆ', benefit: 'ಡಿಜಿಟಲ್ ಸೇವೆಗಳು', eligibility: 'ಎಲ್ಲಾ ರೈತರು', link: 'https://agriwelfare.gov.in/', details: 'ಮಾರುಕಟ್ಟೆ ಮಾಹಿತಿ ಮತ್ತು ಹವಾಮಾನಕ್ಕಾಗಿ ಡಿಜಿಟಲ್ ಮೂಲಸೌಕರ್ಯ.', docs: ['ಆಧಾರ್ ಕಾರ್ಡ್', 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ'] },
        { title: 'ಕ್ಲೀನ್ ಪ್ಲಾಂಟ್ ಪ್ರೋಗ್ರಾಂ', provider: 'ತೋಟಗಾರಿಕೆ ಮಂಡಳಿ', benefit: 'ರೋಗಮುಕ್ತ ಸಸಿಗಳು', eligibility: 'ತೋಟಗಾರರು', link: 'https://www.nhb.gov.in/', details: 'ಉತ್ತಮ ಗುಣಮಟ್ಟದ ಮತ್ತು ರೋಗಮುಕ್ತ ಸಸಿಗಳನ್ನು ಪಡೆಯಲು ಸಹಾಯ.', docs: ['ಭೂಮಿ ದಾಖಲೆ', 'ನೋಂದಣಿ ID'] },
    ],
    // Kannada Dynamic
    "Paddy (Dhan)": "ಭತ್ತ",
    "Wheat": "ಗೋಧಿ",
    "Cotton": "ಹತ್ತಿ",
    "Maize": "ಜೋಳ",
    "Onion": "ಈರುಳ್ಳಿ",
    "Chilli": "ಮೆಣಸಿನಕಾಯಿ",
    "Turmeric": "ಅರಿಶಿನ",
    "Groundnut": "ಕಡಲೆಕಾಯಿ",
    "Soybean": "ಸೋಯಾಬೀನ್",
    "Mustard": "ಸಾಸಿವೆ",
    "Andhra Pradesh": "ಆಂಧ್ರಪ್ರದೇಶ",
    "Telangana": "ತೆಲಂಗಾಣ",
    "Karnataka": "ಕರ್ನಾಟಕ",
    "Maharashtra": "ಮಹಾರಾಷ್ಟ್ರ",
    "Punjab": "ಪಂಜಾಬ್",
    "Uttar Pradesh": "ಉತ್ತರ ಪ್ರದೇಶ",
    "Madhya Pradesh": "ಮಧ್ಯ ಪ್ರದೇಶ",
    "Tamil Nadu": "ತಮಿಳುನಾಡು",
    "Gujarat": "ಗುಜರಾತ್",
    "Haryana": "ಹರಿಯಾಣ",
    noCropDetected: "ಯಾವುದೇ ಬೆಳೆ ಕಂಡುಬಂದಿಲ್ಲ",
    noCropDetectedDesc: "ಈ ವ್ಯವಸ್ಥೆಯು ಕೃಷಿ ಬೆಳೆಗಳನ್ನು ಮಾತ್ರ ವಿಶ್ಲೇಷಿಸುತ್ತದೆ. ದಯವಿಟ್ಟು ಬೆಳೆಯ ಎಲೆ ಅಥವಾ ಕಾಂಡದ ಸ್ಪಷ್ಟ ಫೋಟೋವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    tryAnotherImage: "ಮತ್ತೊಂದು ಚಿತ್ರ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    severity: "ತೀವ್ರತೆ",
    "Copper-based bactericides (preventative)": "ತಾಮ್ರ ಆಧಾರಿತ ಬ್ಯಾಕ್ಟೀರಿಸೈಡ್‌ಗಳು (ಮುನ್ನೆಚ್ಚರಿಕೆ)",
    "Streptomycin (limited use)": "ಸ್ಟ್ರೆಪ್ಟೊಮೈಸಿನ್ (ಸೀಮಿತ ಬಳಕೆ)",
    "Use disease-free seeds": "ರೋಗಮುಕ್ತ ಬೀಜಗಳನ್ನು ಬಳಸಿ",
    "Practice crop rotation": "ಬೆಳೆ ಸರದಿಯನ್ನು ಅಭ್ಯಾಸ ಮಾಡಿ",
    "Avoid working in wet fields": "ಒದ್ದೆಯಾದ ಹೊಲಗಳಲ್ಲಿ ಕೆಲಸ ಮಾಡುವುದನ್ನು ತಪ್ಪಿಸಿ",
    "Disinfect tools regularly": "ಪರಿಕರಗಳನ್ನು ನಿಯಮಿತವಾಗಿ ಸೋಂಕುರಹಿತಗೊಳಿಸಿ",
    "Copper soap": "ತಾಮ್ರದ ಸಾಬೂನು (Copper soap)",
    "Biological controls (Bacillus subtilis)": "ಜೈವಿಕ ನಿಯಂತ್ರಣಗಳು (ಬ್ಯಾಸಿಲಸ್ ಸಬ್ಟಿಲಿಸ್)",
    "Remove infected leaves immediately": "ಸೋಂಕಿತ ಎಲೆಗಳನ್ನು ಕೂಡಲೇ ತೆಗೆದುಹಾಕಿ",
    "Sulfur-based fungicides": "ಗಂಧಕ ಆಧಾರಿತ ಶಿಲೀಂಧ್ರನಾಶಕಗಳು",
    "Neem oil": "ಬೇವು ಎಣ್ಣೆ",
    "Mancozeb": "ಮ್ಯಾಂಕೋಜೆಬ್ (Mancozeb)",
    "Water at roots": "ಬೇರುಗಳ ಬಳಿ ನೀರು ಹಾಕಿ",
    "Improve air circulation": "ಗಾಳಿಯ ಸಂಚಾರವನ್ನು ಸುಧಾರಿಸಿ",
    "Slow recovery potential - chemicals limited": "ಚೇತರಿಸಿಕೊಳ್ಳುವ ಸಾಧ್ಯತೆ ಕಡಿಮೆ - ರಾಸಾಯನಿಕ ಬಳಕೆ ಮಿತವಾಗಿರಲಿ",
    "Soil solarization": "ಮಣ್ಣಿನ ಸೌರ ಚಿಕಿತ್ಸೆ (Soil solarization)",
    "Long-term crop rotation (3-4 years)": "ದೀರ್ಘಕಾಲದ ಬೆಳೆ ಸರದಿ (3-4 ವರ್ಷಗಳು)",
    "Plant resistant varieties": "ರೋಗ ನಿರೋಧಕ ತಳಿಗಳನ್ನು ನಾಟಿ ಮಾಡಿ",
    "Control nematode populations": "ನೆಮಟೋಡ್ ಸಂಖ್ಯೆಯನ್ನು ನಿಯಂತ್ರಿಸಿ",
    "Soil amendments with compost": "ಕಾಂಪೋಸ್ಟ್ ಬಳಸಿ ಮಣ್ಣನ್ನು ಸುಧಾರಿಸಿ",
    "Bio-fungicides (Trichoderma)": "ಜೈವಿಕ ಶಿಲೀಂಧ್ರನಾಶಕಗಳು (Trichoderma)",
    "Potassium bicarbonate": "ಪೋಟ್ಯಾಸಿಯಮ್ ಬೈಕಾರ್ಬನೇಟ್",
    "Myclobutanil": "ಮೈಕ್ಲೋಬುಟಾನಿಲ್",
    "Select resistant varieties": "ನಿರೋಧಕ ತಳಿಗಳನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
    "Avoid overhead watering": "ಮೇಲಿನಿಂದ ನೀರು ಹಾಕುವುದನ್ನು ತಪ್ಪಿಸಿ",
    "Remove infected plant debris": "ಸೋಂಕಿತ ಸಸ್ಯದ ಅವಶೇಷಗಳನ್ನು ತೆಗೆದುಹಾಕಿ",
    "Milk spray (1:10 ratio)": "ಹಾಲಿನ ಸ್ಪ್ರೇ (1:10 ಪ್ರಮಾಣ)",
    "Baking soda solution": "ಬೇಕಿಂಗ್ ಸೋಡಾ ದ್ರಾವಣ",
    "Azoxystrobin": "ಅಜೋಕ್ಸಿಸ್ಟ್ರೋಬಿನ್",
    "Propiconazole": "ಪ್ರೊಪಿಕೊನಜೋಲ್",
    "Plant resistant hybrids": "ನಿರೋಧಕ ಹೈಬ್ರಿಡ್ ತಳಿಗಳನ್ನು ಬಳಸಿ",
    "Monitor nutrient levels (avoid excess N)": "ಪೋಷಕಾಂಶಗಳ ಮಟ್ಟವನ್ನು ಗಮನಿಸಿ",
    "Apply fungicides at early signs": "ಆರಂಭಿಕ ಹಂತದಲ್ಲೇ ಶಿಲೀಂಧ್ರನಾಶಕ ಬಳಸಿ",
    "Sulfur dust": "ಗಂಧಕದ ಪುಡಿ",
    "Remove alternate hosts/weeds": "ಪರ್ಯಾಯ ಆಶ್ರಯದಾತ ಕಳೆಗಳನ್ನು ತೆಗೆಯಿರಿ",
    "Control insect vectors (aphids/thrips)": "ಕೀಟ ವಾಹಕಗಳನ್ನು ನಿಯಂತ್ರಿಸಿ",
    "No direct chemical cure for virus": "ವೈರಸ್‌ಗೆ ನೇರ ರಾಸಾಯನಿಕ ಚಿಕಿತ್ಸೆ ಇಲ್ಲ",
    "Use virus-free certified seeds": "ವೈರಸ್ ಮುಕ್ತ ಪ್ರಮಾಣೀಕೃತ ಬೀಜ ಬಳಸಿ",
    "Control weeds": "ಕಳೆಗಳನ್ನು ನಿಯಂತ್ರಿಸಿ",
    "Remove infected plants immediately (roguing)": "ಸೋಂಕಿತ ಗಿಡಗಳನ್ನು ತಕ್ಷಣ ತೆಗೆದುಹಾಕಿ",
    "Reflective mulches": "ಪ್ರತಿಫಲಿತ ಮಲ್ಚ್‌ಗಳು",
    "Milk spray to prevent mechanical transmission": "ವ್ಯಾಪನೆ ತಡೆಯಲು ಹಾಲು ಸ್ಪ್ರೇ ಮಾಡಿ",
    "Chlorothalonil": "ಕ್ಲೋರೋಥಲೋನಿಲ್",
    "Copper fungicides": "ತಾಮ್ರದ ಶಿಲೀಂಧ್ರನಾಶಕಗಳು",
    "Mulching to prevent soil splash": "ಮಣ್ಣಿನ ಹನಿ ಹಾರುವುದನ್ನು ತಡೆಯಲು ಮಲ್ಚಿಂಗ್ ಮಾಡಿ",
    "Water at base of plant": "ಗಿಡದ ಬುಡಕ್ಕೆ ನೀರು ಹಾಕಿ",
    "Remove lower leaves": "ಕೆಳಗಿನ ಎಲೆಗಳನ್ನು ತೆಗೆದುಹಾಕಿ",
    "Copper spray": "ತಾಮ್ರದ ದ್ರಾವಣ ಸ್ಪ್ರೇ",
    "Biological fungicides": "ಜೈವಿಕ ಶಿಲೀಂಧ್ರನಾಶಕಗಳು",
    "Enhanced air circulation": "ಉತ್ತಮ ಗಾಳಿ ಪ್ರಸರಣ",
    "Captan": "ಕ್ಯಾಪ್ಟಾನ್",
    "Benomyl": "ಬೆನೋಮಿಲ್",
    "Proper drainage": "ಸರಿಯಾದ ಒಳಚರಂಡಿ ವ್ಯವಸ್ಥೆ",
    "Remove infected fruit/twigs": "ಸೋಂಕಿತ ಹಣ್ಣು/ರೆಂಬೆಗಳನ್ನು ತೆಗೆಯಿರಿ",
    "Hot water seed treatment": "ಬಿಸಿ ನೀರು ಬೀಜೋಪಚಾರ",
    "Chlorothalonil (Daconil)": "ಕ್ಲೋರೋಥಲೋನಿಲ್ (ಡಾಕೋನಿಲ್)",
    "Copper-based fungicide (Bordeaux mixture)": "ತಾಮ್ರ ಆಧಾರಿತ ಶಿಲೀಂಧ್ರನಾಶಕ (ಬೋರ್ಡೆಕ್ಸ್ ಮಿಶ್ರಣ)",
    "Improve air circulation (pruning)": "ಸವರುವಿಕೆಯ ಮೂಲಕ ಗಾಳಿ ಪ್ರಸರಣ ಸುಧಾರಿಸಿ",
    "Clean greenhouse structures": "ಹಸಿರುಮನೆ ರಚನೆಗಳನ್ನು ಸ್ವಚ್ಛಗೊಳಿಸಿ",
    "Neem oil spray": "ಬೇವಣ್ಣೆ ಸ್ಪ್ರೇ",
    "Compost tea": "ಕಾಂಪೋಸ್ಟ್ ಟೀ",
    "Ridomil Gold": "ರಿಡೋಮಿಲ್ ಗೋಲ್ಡ್",
    "Destroy culled potatoes": "ಅನಾರೋಗ್ಯಕರ ಆಲೂಗಡ್ಡೆಗಳನ್ನು ನಾಶಮಾಡಿ",
    "Plant certified seed": "ಪ್ರಮಾಣೀಕೃತ ಬೀಜಗಳನ್ನು ಬಿತ್ತಿ",
    "Monitor weather (cool/wet favors blight)": "ಹವಾಮಾನದ ಮೇಲೆ ನಿಗಾ ಇರಿಸಿ",
    "Kill vines before harvest": "ಕೊಯ್ಲಿಗಿಂತ ಮುನ್ನ ಬಳ್ಳಿಗಳನ್ನು ಒಣಗಿಸಿ",
    "Copper products": "ತಾಮ್ರದ ಉತ್ಪನ್ನಗಳು",
    "Hydrogen dioxide": "ಹೈಡ್ರೋಜನ್ ಡೈಆಕ್ಸೈಡ್",
    "Continue regular monitoring": "ನಿಯಮಿತವಾಗಿ ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ",
    "Maintain proper irrigation": "ಸರಿಯಾದ ನೀರಾವರಿಯನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಿ",
    "Apply balanced fertilizers": "ಸಮತೋಲಿತ ರಸಗೊಬ್ಬರಗಳನ್ನು ಬಳಸಿ",
    "Disinfect tools": "ಪರಿಕರಗಳನ್ನು ಸೋಂಕುಮುಕ್ತಗೊಳಿಸಿ",
    "Crop rotation": "ಬೆಳೆ ಸರದಿ",
    "Please upload a clear image of a crop leaf": "ಬೆಳೆ ಎಲೆಯ ಸ್ಪಷ್ಟ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    "Ensure the image is well-lit": "ಚಿತ್ರವು ಉತ್ತಮ ಬೆಳಕಿನಲ್ಲಿದೆ ಎಂದು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ",
    "Focus on the plant tissue": "ಸಸ್ಯದ ಅಂಗಾಂಶಗಳ ಮೇಲೆ ಗಮನಹರಿಸಿ"
};

const ta = {
    detect: "கண்டறிதல்",
    dashboard: "முகப்பு",
    history: "வரலாறு",
    weather: "வானிலை",
    mandi: "சந்தை விலை",
    schemes: "திட்டங்கள்",
    community: "விவசாயி குழு",
    login: "ஏஜென்ட்",
    logout: "வெளியேறு",
    welcome: "நிபுணர் பாதுகாப்பு",
    homeSubtitle: "நோய்களைக் கண்டறிந்து நிபுணர்களுடன் ஆலோசிக்கவும்.",
    startDiagnosis: "தொடங்கவும்",
    viewWeather: "வானிலை பார்க்க",
    trustedBy: "20,000+ விவசாயிகளின் நம்பிக்கை",
    accuracy: "98% துல்லியம்",
    instantReport: "உடனடி அறிக்கை",
    expertHelp: "நிபுணர் உதவி",
    aiCropDoctor: "AI பயிர் மருத்துவர்",
    detectionSubtitle: "இலையின் புகைப்படத்தை எடுக்கவும். AI நோயைக் கண்டறியும்.",
    readyToScan: "ஸ்கேன் செய்யத் தயாரா?",
    dropImage: "படத்தை இங்கே போடவும்",
    analyzeInfection: "பகுப்பாய்வு",
    computing: "கணக்கிடுகிறது...",
    recommendedRecovery: "பரிந்துரைக்கப்பட்ட தீர்வு",
    biologicalMeasures: "இயற்கை முறைகள்",
    saveToCloud: "சேமிக்கவும்",
    today: 'இன்று',
    delete: 'நீக்கு',
    state: 'மாநிலம்',
    confirmDelete: 'இதை நீக்க விரும்புகிறீர்களா?',
    mandiTitle: "சந்தை நிலவரம்",
    mandiSubtitle: "நாடு முழுவதும் உள்ள சந்தை விலைகளை அறியவும்.",
    cropName: "பயிர் பெயர்",
    market: "சந்தை",
    price: "விலை (₹/குவிண்டால்)",
    trend: "போக்கு",
    schemesTitle: "அரசு திட்டங்கள்",
    schemesSubtitle: "விவசாயிகளுக்கான நிதியுதவி மற்றும் மானியங்கள்.",
    applyNow: "விண்ணப்பிக்கவும்",
    details: "விவரங்கள்",
    close: "மூடு",
    aboutScheme: "திட்டம் பற்றி",
    reqDocs: "தேவையான ஆவணங்கள்",
    communityTitle: "விவசாயக் குழு",
    communitySubtitle: "விவாதிக்கவும் மற்றும் பகிரவும்.",
    newPost: "புதிய விவாதம்",
    replies: "பதில்கள்",
    welcomeBack: "நல்வரவு",
    createAccount: "கணக்கை உருவாக்கு",
    secureLogin: "பாதுகாப்பான உள்நுழைவு",
    googleLogin: "Google மூலம் தொடரவும்",
    useEmail: "மின்னஞ்சல் பயன்படுத்தவும்",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    signIn: "உள்நுழையவும்",
    joinNow: "இணையவும்",
    needAccount: "புதிய கணக்கு?",
    existingMember: "உள்நுழையவும்",
    goodMorning: "காலை வணக்கம்",
    goodAfternoon: "மதிய வணக்கம்",
    goodEvening: "மாலை வணக்கம்",
    dashboardSubtitle: "உங்கள் பயிர்களின் நிலை.",
    overallHealth: "பயிர் ஆரோக்கியம்",
    activeAlerts: "எச்சரிக்கைகள்",
    tasksCompleted: "முடித்த பணிகள்",
    performanceIndex: "செயல்திறன்",
    localWeather: "உள்ளூர் வானிலை",
    detailedForecast: "முழு அறிக்கை",
    detectionHistory: "வரலாறு",
    liveMarket: "நேரடி விலை",
    updated: "புதுப்பிக்கப்பட்டது",
    selectState: "மாநிலம் தேர்வு",
    searchMandi: "தேடுக...",
    minPrice: "குறைந்தபட்சம்",
    maxPrice: "அதிகபட்சம்",
    modalPrice: "சராசரி விலை",
    searchCity: "நகரம் தேடுக...",
    humidity: "ஈரப்பதம்",
    windSpeed: "காற்றின் வேகம்",
    precipitation: "மழைப்பொழிவு",
    filterPlaceholder: "தேடுக...",
    all: "அனைத்தும்",
    healthy: "ஆரோக்கியம்",
    issues: "பிரச்சனைகள்",
    highSeverity: "தீவிரம்",
    loadingDiscussions: "ஏற்றப்படுகிறது...",
    noDiscussions: "விவாதங்கள் இல்லை.",
    loadingRecords: "ஏற்றப்படுகிறது...",
    noRecords: "தரவு இல்லை",
    exportPDF: "PDF பதிவிறக்கம்",
    confidence: "நம்பிக்கை",
    cloudSynced: "ஒத்திசைக்கப்பட்டது",
    unknown: "தெரியவில்லை",
    applyWebsite: "இணையதளத்தில் விண்ணப்பிக்கவும்",
    deleteSuccess: "நீக்கப்பட்டது!",
    deleteFail: "தோல்வி...",
    newDiscussion: "புதிய விவாதம்",
    shareTip: "கேள்வி கேட்கவும்...",
    cancel: "ரத்து",
    post: "பதிவிடு",
    regionalGroups: "பிராந்திய குழுக்கள்",
    regionalSubtitle: "உங்கள் மொழியில் பேசுங்கள்",
    howItWorks: "இது எப்படி வேலை செய்கிறது",
    singleSubject: "ஒற்றை பொருள்",
    singleSubjectDesc: "இலை முக்கிய மையமாக இருப்பதை உறுதி செய்யவும்.",
    naturalLight: "இயற்கை ஒளி",
    naturalLightDesc: "சிறந்த முடிவுகளுக்கு நல்ல ஒளியைப் பயன்படுத்தவும்.",
    highContext: "உயர் சூழல்",
    highContextDesc: "போதுமான சுற்றியுள்ள விவரங்களைப் பிடிக்கவும்.",

    // Result Translations (Tamil)
    "Healthy": "ஆரோக்கியமானது",
    "High": "அதிக",
    "Medium": "நடுத்தர",
    "Low": "குறைந்த",
    "None": "இல்லை",
    "General Plant": "பொதுவான தாவரம்",
    "Multiple Crops": "பல்வேறு பயிர்கள்",
    "Beans / General": "பீன்ஸ் / பொதுவானது",
    "Tomato / Potato / Cotton": "தக்காளி / உருளைக்கிழங்கு / பருத்தி",
    "Corn / Wheat": "சோளம் / கோதுமை",
    "General": "பொது",
    "Tomato / Wheat": "தக்காளி / கோதுமை",
    "Berries / Beans": "பெர்ரி / பீன்ஸ்",
    "Tomato": "தக்காளி",
    "Potato": "உருளைக்கிழங்கு",
    "CropAdvisory": "பயிர் ஆலோசனை",
    "organicSolutions": "இயற்கை தீர்வுகள்",
    "healthyMessageTitle": "நல்ல செய்தி! உங்கள் செடி ஆரோக்கியமாக உள்ளது.",
    "healthyMessageBody": "சிறந்த முடிவுகளுக்கு தொடர்ந்து கண்காணிக்கவும்.",
    "Powdery Mildew": "சாம்பல் நோய்",
    "Bacterial Blight": "பாக்டீரியா வாடல் நோய்",
    "Verticillium Wilt": "வாடல் நோய்",
    "Leaf Rust": "இலை துரு நோய்",
    "Viral Mosaic / Chlorosis": "வைரஸ் தேமல் நோய்",
    "Septoria Leaf Spot": "இலைப்புள்ளி நோய்",
    "Anthracnose (Bird's Eye Spot)": "ஆந்த்ராக்னோஸ்",
    "Tomato Leaf Mold": "தக்காளி இலை பூஞ்சை",
    "Potato Late Blight": "உருளைக்கிழங்கு வாடல் நோய்",
    "Not a Crop": "பயிர் அல்ல",

    schemesData: [
        { title: 'PM- கிசான் சம்மான் நிதி', provider: 'மத்திய அரசு', benefit: '₹6,000/ஆண்டு', eligibility: 'சிறு விவசாயிகள்', link: 'https://pmkisan.gov.in/', details: 'விவசாய குடும்பங்களுக்கு ஆண்டுக்கு ₹6,000 நிதியுதவி.', docs: ['ஆதார் அட்டை', 'நில ஆவணங்கள்', 'வங்கி கணக்கு'] },
        { title: 'மண் சுகாதார அட்டை', provider: 'வேளாண் துறை', benefit: 'மண் ஆய்வு', eligibility: 'அனைத்து விவசாயிகள்', link: 'https://soilhealth.dac.gov.in/', details: 'மண்ணின் சத்துக்கள் பற்றிய தகவல்.', docs: ['மண் மாதிரி', 'ஆதார்', 'மொபைல் எண்'] },
        { title: 'PM பயிர் காப்பீடு', provider: 'மத்திய அரசு', benefit: 'பயிர் காப்பீடு', eligibility: 'KCC வைத்திருப்போர்', link: 'https://pmfby.gov.in/', details: 'பயிர் இழப்புக்கு எதிரான காப்பீடு.', docs: ['விதைப்பு சான்றிதழ்', 'நில பதிவு', 'ID ஆதாரம்'] },
        { title: 'கிசான் கிரெடிட் கார்டு', provider: 'SBI', benefit: 'குறைந்த வட்டி கடன்', eligibility: 'தகுதிவாய்ந்த விவசாயிகள்', link: 'https://www.myscheme.gov.in/schemes/kcc', details: 'விவசாய தேவைகளுக்கான கடன் வசதி.', docs: ['விண்ணப்பம்', 'நில ஆவணங்கள்', 'புகைப்படம்'] },
        { title: 'குசும் திட்டம்', provider: 'MNRE', benefit: 'சூரிய பம்புகள்', eligibility: 'விவசாயிகள்', link: 'https://pmkusum.mnre.gov.in/', details: 'சூரிய சக்தி பம்புகளுக்கான மானியம்.', docs: ['விண்ணப்பம்', 'அடையாள அட்டை', 'நில ஆவணங்கள்'] },
        { title: 'வேளாண் உள்கட்டமைப்பு நிதி', provider: 'மத்திய அரசு', benefit: 'கிடங்கு மானியம்', eligibility: 'விவசாயிகள்', link: 'https://theagriculturefund.nic.in/', details: 'பயிர் சேமிப்புக்கான நிதியுதவி.', docs: ['திட்ட அறிக்கை', 'KYC', 'வங்கி ஒப்புதல்'] },
    ],
    // Tamil Dynamic
    "Paddy (Dhan)": "நெல்",
    "Wheat": "கோதுமை",
    "Cotton": "பருத்தி",
    "Maize": "சோளம்",
    "Onion": "வெங்காயம்",
    "Chilli": "மிளகாய்",
    "Turmeric": "மஞ்சள்",
    "Groundnut": "நிலக்கடலை",
    "Soybean": "சோயாபீன்",
    "Mustard": "கடுகு",
    "Andhra Pradesh": "ஆந்திர பிரதேசம்",
    "Telangana": "தெலுங்கானா",
    "Karnataka": "கர்நாடகா",
    "Maharashtra": "மகாராஷ்டிரா",
    "Punjab": "பஞ்சாப்",
    "Uttar Pradesh": "உத்தரப் பிரதேசம்",
    "Madhya Pradesh": "மத்தியப் பிரதேசம்",
    "Tamil Nadu": "தமிழ்நாடு",
    "Gujarat": "குஜராத்",
    "Haryana": "ஹரியானா",
    noCropDetected: "பயிர் எதுவும் கண்டறியப்படவில்லை",
    noCropDetectedDesc: "இந்த அமைப்பு பயிர்களை மட்டுமே பகுப்பாய்வு செய்கிறது. பயிர் இலை அல்லது தண்டின் தெளிவான புகைப்படத்தைப் பதிவேற்றவும்.",
    tryAnotherImage: "மற்றொரு படத்தை முயற்சிக்கவும்",
    severity: "தீவிரம்",
    "Copper-based bactericides (preventative)": "தாமிரம் கலந்த பாக்டீரியா கொல்லிகள் (தடுப்பு)",
    "Streptomycin (limited use)": "ஸ்ட்ரெப்டோமைசின் (வரையறுக்கப்பட்ட பயன்பாடு)",
    "Use disease-free seeds": "நோய் இல்லாத விதைகளைப் பயன்படுத்துங்கள்",
    "Practice crop rotation": "பயிர் சுழற்சியைப் பின்பற்றுங்கள்",
    "Avoid working in wet fields": "ஈரமான வயல்களில் வேலை செய்வதைத் தவிர்க்கவும்",
    "Disinfect tools regularly": "கருவிகளைத் தொடர்ந்து கிருமி நீக்கம் செய்யவும்",
    "Copper soap": "தாமிர சோப் (Copper soap)",
    "Biological controls (Bacillus subtilis)": "உயிரியல் கட்டுப்பாடுகள் (பேசிலஸ் சப்டிலிஸ்)",
    "Remove infected leaves immediately": "பாதிக்கப்பட்ட இலைகளை உடனடியாக அகற்றவும்",
    "Sulfur-based fungicides": "கந்தகம் சார்ந்த பூஞ்சை காளான் கொல்லிகள்",
    "Neem oil": "வேப்ப எண்ணெய்",
    "Mancozeb": "மேன்கோசெப் (Mancozeb)",
    "Water at roots": "வேர்களுக்கு நீர் பாய்ச்சுவது",
    "Improve air circulation": "காற்று சுழற்சியை மேம்படுத்தவும்",
    "Slow recovery potential - chemicals limited": "மீட்பு வாய்ப்பு குறைவு - இரசாயனங்கள் வரையறுக்கப்பட்டவை",
    "Soil solarization": "மண் சூரிய ஒளி சிகிச்சை (Soil solarization)",
    "Long-term crop rotation (3-4 years)": "நீண்ட கால பயிர் சுழற்சி (3-4 ஆண்டுகள்)",
    "Plant resistant varieties": "நோய் எதிர்ப்பு ரகங்களை பயிரிடவும்",
    "Control nematode populations": "நெமடோட் எண்ணிக்கையை கட்டுப்படுத்தவும்",
    "Soil amendments with compost": "உரத்தைப் பயன்படுத்தி மண்ணை மேம்படுத்தவும்",
    "Bio-fungicides (Trichoderma)": "உயிரியல் பூஞ்சை காளான் கொல்லிகள் (Trichoderma)",
    "Potassium bicarbonate": "பொட்டாசியம் பைகார்பனேட்",
    "Myclobutanil": "மைக்லோபுட்டானில்",
    "Select resistant varieties": "எதிர்ப்புத் திறன் கொண்ட ரகங்களைத் தேர்ந்தெடுக்கவும்",
    "Avoid overhead watering": "செடிகளின் மேல் தண்ணீர் ஊற்றுவதைத் தவிர்க்கவும்",
    "Remove infected plant debris": "பாதிக்கப்பட்ட செடி கழிவுகளை அகற்றவும்",
    "Milk spray (1:10 ratio)": "பால் தெளிப்பு (1:10 விகிதம்)",
    "Baking soda solution": "சமையல் சோடா கரைசல்",
    "Azoxystrobin": "அசோக்சிஸ்ட்ரோபின்",
    "Propiconazole": "புரோபிகோனசோல்",
    "Plant resistant hybrids": "எதிர்ப்புத் திறன் கொண்ட கலப்பினங்களை நடவும்",
    "Monitor nutrient levels (avoid excess N)": "ஊட்டச்சத்து அளவைக் கண்காணிக்கவும்",
    "Apply fungicides at early signs": "ஆரம்ப அறிகுறிகளிலேயே பூஞ்சைக் கொல்லிகளைப் பயன்படுத்தவும்",
    "Sulfur dust": "சல்பர் தூள்",
    "Remove alternate hosts/weeds": "மாற்று களைகளை அகற்றவும்",
    "Control insect vectors (aphids/thrips)": "பூச்சிக் கடத்திகளைக் கட்டுப்படுத்தவும்",
    "No direct chemical cure for virus": "வைரஸுக்கு நேரடி இரசாயன சிகிச்சை இல்லை",
    "Use virus-free certified seeds": "வைரஸ் இல்லாத சான்றளிக்கப்பட்ட விதைகளைப் பயன்படுத்தவும்",
    "Control weeds": "களைகளைக் கட்டுப்படுத்தவும்",
    "Remove infected plants immediately (roguing)": "பாதிக்கப்பட்ட செடிகளை உடனே அகற்றவும்",
    "Reflective mulches": "பிரதிபலிப்பு தழைக்கூளம்",
    "Milk spray to prevent mechanical transmission": "பரவுவதைத் தடுக்க பால் தெளிக்கவும்",
    "Chlorothalonil": "குளோரோதலோனில்",
    "Copper fungicides": "செப்பு பூஞ்சைக் கொல்லிகள்",
    "Mulching to prevent soil splash": "மண் சிதறாமல் தடுக்க தழைக்கூளம் இடவும்",
    "Water at base of plant": "செடியின் அடியில் தண்ணீர் ஊற்றவும்",
    "Remove lower leaves": "கீழ் இலைகளை அகற்றவும்",
    "Copper spray": "காப்பர் ஸ்ப்ரே",
    "Biological fungicides": "உயிரியல் பூஞ்சைக் கொல்லிகள்",
    "Enhanced air circulation": "மேம்படுத்தப்பட்ட காற்று சுழற்சி",
    "Captan": "கேப்டன்",
    "Benomyl": "பெனோமியில்",
    "Proper drainage": "சரியான வடிகால் வசதி",
    "Remove infected fruit/twigs": "பாதிக்கப்பட்ட பழங்கள்/கிளைகளை அகற்றவும்",
    "Hot water seed treatment": "சுடுநீரில் விதை சிகிச்சை",
    "Chlorothalonil (Daconil)": "குளோரோதலோனில் (டாக்கோனில்)",
    "Copper-based fungicide (Bordeaux mixture)": "காப்பர் அடிப்படையிலான பூஞ்சைக்கொல்லி (போர்டோ கலவை)",
    "Improve air circulation (pruning)": "கத்தரித்தல் மூலம் காற்று சுழற்சியை மேம்படுத்தவும்",
    "Clean greenhouse structures": "பசுமை இல்ல அமைப்புகளைச் சுத்தம் செய்யவும்",
    "Neem oil spray": "வேப்ப எண்ணெய் தெளிக்கவும்",
    "Compost tea": "உரத் தேநீர் (Compost tea)",
    "Ridomil Gold": "ரிடோமில் கோல்ட்",
    "Destroy culled potatoes": "பாதிக்கப்பட்ட உருளைக்கிழங்குகளை அழிக்கவும்",
    "Plant certified seed": "சான்றளிக்கப்பட்ட விதைகளைப் பயிரிடவும்",
    "Monitor weather (cool/wet favors blight)": "வானிலை மாற்றத்தைக் கவனிக்கவும்",
    "Kill vines before harvest": "அறுவடைக்கு முன் கொடிகளை அழிக்கவும்",
    "Copper products": "காப்பர் தயாரிப்புகள்",
    "Hydrogen dioxide": "ஹைட்ரஜன் டை ஆக்சைடு",
    "Continue regular monitoring": "தொடர்ந்து கண்காணித்து வாருங்கள்",
    "Maintain proper irrigation": "சரியான நீர் பாசனத்தை பராமரிக்கவும்",
    "Apply balanced fertilizers": "சமச்சீர் உரங்களைப் பயன்படுத்துங்கள்",
    "Disinfect tools": "கருவிகளைச் சுத்தப்படுத்தவும்",
    "Crop rotation": "பயிர் சுழற்சி",
    "Please upload a clear image of a crop leaf": "பயிர் இலையின் தெளிவான படத்தை பதிவேற்றவும்",
    "Ensure the image is well-lit": "படம் நல்ல வெளிச்சத்தில் இருப்பதை உறுதி செய்யவும்",
    "Focus on the plant tissue": "செடியின் திசுக்களில் கவனம் செலுத்துங்கள்"
};

const ml = {
    detect: "രോഗനിർണ്ണയം",
    dashboard: "ഡാഷ്ബോർഡ്",
    history: "ചരിത്രം",
    weather: "കാലാവസ്ഥ",
    mandi: "വിപണി വില",
    schemes: "പദ്ധതികൾ",
    community: "കർഷക കൂട്ടായ്മ",
    login: "ലോഗിൻ",
    logout: "പുറത്തുകടക്കുക",
    welcome: "വിളകൾക്ക് വിദഗ്ദ്ധ പരിചരണം",
    homeSubtitle: "രോഗങ്ങൾ തിരിച്ചറിയുക, വിദഗ്ധരുമായി സംസാരിക്കുക.",
    startDiagnosis: "പരിശോധന തുടങ്ങുക",
    viewWeather: "കാലാവസ്ഥ അറിയുക",
    trustedBy: "20,000+ കർഷകർ വിശ്വസിക്കുന്നു",
    accuracy: "98% കൃത്യത",
    instantReport: "പെട്ടെന്നുള്ള റിപ്പോർട്ട്",
    expertHelp: "വിദഗ്ദ്ധ സഹായം",
    aiCropDoctor: "AI ക്രോപ്പ് ഡോക്ടർ",
    detectionSubtitle: "ഇലയുടെ ഫോട്ടോ എടുക്കുക. AI രോഗം കണ്ടെത്തും.",
    readyToScan: "സ്കാൻ ചെയ്യാൻ തയ്യാറാണോ?",
    dropImage: "ചിത്രം ഇവിടെ നൽകുക",
    analyzeInfection: "വിശകലനം ചെയ്യുക",
    computing: "പരിശോധിക്കുന്നു...",
    recommendedRecovery: "ശുപാർശ ചെയ്യുന്ന ചികിത്സ",
    biologicalMeasures: "ജൈവ മാർഗ്ഗങ്ങൾ",
    saveToCloud: "റിപ്പോർട്ട് സൂക്ഷിക്കുക",
    today: 'ഇന്ന്',
    delete: 'നീക്കം ചെയ്യുക',
    state: 'സംസ്ഥാനം',
    confirmDelete: 'ഇത് നീക്കം ചെയ്യാൻ ആഗ്രഹിക്കുന്നുവോ?',
    mandiTitle: "വിപണി നിരക്കുകൾ",
    mandiSubtitle: "വിളകളുടെ തത്സമയ വിപണി വിലകൾ അറിയുക.",
    cropName: "വിള",
    market: "വിപണി",
    price: "വില (₹/ക്വിന്റൽ)",
    trend: "പ്രവണത",
    schemesTitle: "സർക്കാർ പദ്ധതികൾ",
    schemesSubtitle: "കർഷകർക്കുള്ള ധനസഹായവും സബ്‌സിഡിയും.",
    applyNow: "അപേക്ഷിക്കുക",
    details: "വിശദാംശങ്ങൾ",
    close: "അടയ്ക്കുക",
    aboutScheme: "പദ്ധതിയെക്കുറിച്ച്",
    reqDocs: "ആവശ്യമായ രേഖകൾ",
    communityTitle: "കർഷക വേദി",
    communitySubtitle: "ചർച്ച ചെയ്യുക, പങ്കിടുക.",
    newPost: "ചർച്ച തുടങ്ങുക",
    replies: "മറുപടികൾ",
    welcomeBack: "സ്വാഗതം",
    createAccount: "അക്കൗണ്ട് ഉണ്ടാക്കുക",
    secureLogin: "സുരക്ഷിത ലോഗിൻ",
    googleLogin: "Google വഴി തുടരുക",
    useEmail: "ഇമെയിൽ ഉപയോഗിക്കുക",
    email: "ഇമെയിൽ",
    password: "പാസ്‌വേഡ്",
    signIn: "സൈൻ ഇൻ",
    joinNow: "ചേരുക",
    needAccount: "അക്കൗണ്ട് വേണോ?",
    existingMember: "ലോഗിൻ ചെയ്യൂ",
    goodMorning: "സുപ്രഭാതം",
    goodAfternoon: "ശുഭ മദ്ധ്യാഹ്നം",
    goodEvening: "ശുഭ സന്ധ്യ",
    dashboardSubtitle: "നിങ്ങളുടെ വിളകളുടെ അവസ്ഥ.",
    overallHealth: "വിള ആരോഗ്യം",
    activeAlerts: "അറിയിപ്പുകൾ",
    tasksCompleted: "പൂർത്തിയാക്കിയവ",
    performanceIndex: "പ്രകടനം",
    localWeather: "പ്രാദേശിക കാലാവസ്ഥ",
    detailedForecast: "വിശദമായ റിപ്പോർട്ട്",
    detectionHistory: "പരിശോധന ചരിത്രം",
    liveMarket: "തത്സമയ വില",
    updated: "പുതുക്കിയത്",
    selectState: "സംസ്ഥാനം തിരഞ്ഞെടുക്കുക",
    searchMandi: "തിരയുക...",
    minPrice: "കുറഞ്ഞ വില",
    maxPrice: "കൂടിയ വില",
    modalPrice: "ശരാശരി വില",
    searchCity: "നഗരം തിരയുക...",
    humidity: "ഈർപ്പം",
    windSpeed: "കാറ്റിന്റെ വേഗത",
    precipitation: "മഴ",
    filterPlaceholder: "തിരയുക...",
    all: "എല്ലാം",
    healthy: "ആരോഗ്യമുള്ളവ",
    issues: "പ്രശ്നങ്ങൾ",
    highSeverity: "ഗുരുതരം",
    loadingDiscussions: "ലോഡുചെയ്യുന്നു...",
    noDiscussions: "ചർച്ചകൾ ഇല്ല.",
    loadingRecords: "ശേഖരിക്കുന്നു...",
    noRecords: "വിവരങ്ങൾ ഇല്ല",
    exportPDF: "PDF ഡൗൺലോഡ്",
    confidence: "വിശ്വാസ്യത",
    cloudSynced: "സിങ്ക് ചെയ്തു",
    unknown: "അജ്ഞാതം",
    applyWebsite: "വെബ്‌സൈറ്റിൽ അപേക്ഷിക്കുക",
    deleteSuccess: "നീക്കം ചെയ്തു!",
    deleteFail: "പരാജയപ്പെട്ടു...",
    newDiscussion: "പുതിയ ചർച്ച",
    shareTip: "ചോദ്യം ചോദിക്കുക...",
    cancel: "റദ്ദാക്കുക",
    post: "പോസ്റ്റ്",
    regionalGroups: "പ്രാദേശിക ഗ്രൂപ്പുകൾ",
    howItWorks: "ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു",
    singleSubject: "ഒറ്റ വിഷയം",
    singleSubjectDesc: "ഇല പ്രധാന ഫോക്കസ് ആണെന്ന് ഉറപ്പാക്കുക.",
    naturalLight: "സ്വാഭാവിക വെളിച്ചം",
    naturalLightDesc: "മികച്ച ഫലങ്ങൾക്കായി നല്ല വെളിച്ചം ഉപയോഗിക്കുക.",
    highContext: "ഉയർന്ന സന്ദർഭം",
    highContextDesc: "മതിയായ ചുറ്റുപാടുള്ള വിശദാംശങ്ങൾ പകർത്തുക.",
    regionalSubtitle: "സ്വന്തം ഭാഷയിൽ സംസാരിക്കൂ",

    // Result Translations (Malayalam)
    "Healthy": "ആരോഗ്യമുള്ളത്",
    "High": "കൂടുതൽ",
    "Medium": "ഇടത്തരം",
    "Low": "കുറഞ്ഞ",
    "None": "ഇല്ല",
    "General Plant": "പൊതുവായ ചെടി",
    "Multiple Crops": "വിവിധ വിളകൾ",
    "Beans / General": "പയർ / പൊതുവായ",
    "Tomato / Potato / Cotton": "തക്കാളി / ഉരുളക്കിഴങ്ങ് / പരുത്തി",
    "Corn / Wheat": "ചോളം / ഗോതമ്പ്",
    "General": "പൊതു",
    "Tomato / Wheat": "തക്കാളി / ഗോതമ്പ്",
    "Berries / Beans": "ബെറികൾ / പയർ",
    "Tomato": "തക്കാളി",
    "Potato": "ഉരുളക്കിഴങ്ങ്",
    "CropAdvisory": "വിള ഉപദേശം",
    "organicSolutions": "ജൈവ പരിഹാരങ്ങൾ",
    "healthyMessageTitle": "നല്ല വാർത്ത! നിങ്ങളുടെ ചെടി ആരോഗ്യകരമാണ്.",
    "healthyMessageBody": "മികച്ച ഫലങ്ങൾക്കായി പതിവായി നിരീക്ഷിക്കുക.",
    "Powdery Mildew": "പൂപ്പൽ രോഗം",
    "Bacterial Blight": "ബാക്ടീരിയൽ വാട്ടം",
    "Verticillium Wilt": "വാട്ടം",
    "Leaf Rust": "ഇല തുരുമ്പ്",
    "Viral Mosaic / Chlorosis": "വൈറൽ മൊസൈക്",
    "Septoria Leaf Spot": "ഇലപ്പുള്ളി രോഗം",
    "Anthracnose (Bird's Eye Spot)": "ആന്ത്രാക്നോസ്",
    "Tomato Leaf Mold": "തക്കാളി ഇല പൂപ്പൽ",
    "Potato Late Blight": "ഉരുളക്കിഴങ്ങ് ലൈറ്റ് ബ്ലൈറ്റ്",
    "Not a Crop": "വിളയല്ല",

    schemesData: [
        { title: 'പിഎം-കിസാൻ സമ്മാൻ നിധി', provider: 'കേന്ദ്ര സർക്കാർ', benefit: '₹6,000/വർഷം', eligibility: 'ചെറുകിട കർഷകർ', link: 'https://pmkisan.gov.in/', details: 'കർഷക കുടുംബങ്ങൾക്ക് വർഷം 6,000 രൂപ ധനസഹായം.', docs: ['ആധാർ കാർഡ്', 'ഭൂമി രേഖകൾ', 'ബാങ്ക് അക്കൗണ്ട്'] },
        { title: 'സോയിൽ ഹെൽത്ത് കാർഡ്', provider: 'കൃഷി വകുപ്പ്', benefit: 'മണ്ണ് പരിശോധന', eligibility: 'എല്ലാ കർഷകർക്കും', link: 'https://soilhealth.dac.gov.in/', details: 'മണ്ണിലെ പോഷകങ്ങളെക്കുറിച്ചുള്ള വിവരങ്ങൾ.', docs: ['മണ്ണ് സാമ്പിൾ', 'ആധാർ', 'മൊബൈൽ നമ്പർ'] },
        { title: 'പിഎം ഫസൽ ബീമാ യോജന', provider: 'കേന്ദ്ര സർക്കാർ', benefit: 'വിള ഇൻഷുറൻസ്', eligibility: 'KCC ഉള്ളവർക്ക്', link: 'https://pmfby.gov.in/', details: 'വിളനാശത്തിനെതിരായ സംരക്ഷണം.', docs: ['കൃഷി സർട്ടിഫിക്കറ്റ്', 'ഭൂമി രേഖ', 'ID കാർഡ്'] },
        { title: 'കിസാൻ ക്രെഡിറ്റ് കാർഡ്', provider: 'SBI', benefit: 'കുറഞ്ഞ പലിശക്ക് വായ്പ', eligibility: 'യോഗ്യരായ കർഷകർ', link: 'https://www.myscheme.gov.in/schemes/kcc', details: 'കൃഷി ആവശ്യങ്ങൾക്കുള്ള വായ്പാ സൗകര്യം.', docs: ['അപേക്ഷ', 'ഭൂമി രേഖകൾ', 'ഫോട്ടോ'] },
        { title: 'കുസും പദ്ധതി', provider: 'MNRE', benefit: 'സോളാർ പമ്പുകൾ', eligibility: 'കർഷകർ', link: 'https://pmkusum.mnre.gov.in/', details: 'സോളാർ പമ്പുകൾ സ്ഥാപിക്കുന്നതിനുള്ള സബ്‌സിഡി.', docs: ['അപേക്ഷ', 'തിരിച്ചറിയൽ കാർഡ്', 'ഭൂമി രേഖകൾ'] },
        { title: 'അഗ്രി-ഇൻഫ്രാ ഫണ്ട്', provider: 'കേന്ദ്ര സർക്കാർ', benefit: 'സംഭരണ സബ്‌സിഡി', eligibility: 'കർഷകർ', link: 'https://theagriculturefund.nic.in/', details: 'വിളവെടുപ്പിന് ശേഷമുള്ള സൗകര്യങ്ങൾക്കായി വായ്പ.', docs: ['പദ്ധതി രേഖ', 'KYC', 'ബാങ്ക് അംഗീകാരം'] },
    ],
    // Malayalam Dynamic
    "Paddy (Dhan)": "നെല്ല്",
    "Wheat": "ഗോതമ്പ്",
    "Cotton": "പരുത്തി",
    "Maize": "ചോളം",
    "Onion": "ഉള്ളി",
    "Chilli": "മുളക്",
    "Turmeric": "മഞ്ഞൾ",
    "Groundnut": "നിലക്കടല",
    "Soybean": "സോയാബീൻ",
    "Mustard": "കടുക്",
    "Andhra Pradesh": "ആന്ധ്രാപ്രദേശ്",
    "Telangana": "തെലങ്കാന",
    "Karnataka": "കർണാടക",
    "Maharashtra": "മഹാരാഷ്ട്ര",
    "Punjab": "പഞ്ചാബ്",
    "Uttar Pradesh": "ഉത്തർപ്രദേശ്",
    "Madhya Pradesh": "മധ്യപ്രദേശ്",
    "Tamil Nadu": "തമിഴ്നാട്",
    "Gujarat": "ഗുജറാത്ത്",
    "Haryana": "ഹരിയാന",
    noCropDetected: "വിളകളൊന്നും കണ്ടെത്തിയില്ല",
    noCropDetectedDesc: "ഈ സിസ്റ്റം വിളകളെ മാത്രമേ വിശകലനം ചെയ്യുകയുള്ളൂ. ഒരു വിളയുടെ ഇലയുടെയോ തണ്ടിന്റെയോ വ്യക്തമായ ചിത്രം അപ്‌ലോഡ് ചെയ്യുക.",
    tryAnotherImage: "മറ്റൊരു ചിത്രം സ്കാൻ ചെയ്യുക",
    severity: "തീവ്രത",
    "Copper-based bactericides (preventative)": "ചെമ്പ് അടിസ്ഥാനമാക്കിയുള്ള ബാക്ടീരിസൈഡുകൾ (പ്രതിരോധം)",
    "Streptomycin (limited use)": "സ്ട്രെപ്റ്റോമൈസിൻ (പരിമിതമായ ഉപയോഗം)",
    "Use disease-free seeds": "രോഗമില്ലാത്ത വിത്തുകൾ ഉപയോഗിക്കുക",
    "Practice crop rotation": "വിള പരിക്രമണം നടപ്പിലാക്കുക",
    "Avoid working in wet fields": "നനഞ്ഞ പാടങ്ങളിൽ ജോലി ചെയ്യുന്നത് ഒഴിവാക്കുക",
    "Disinfect tools regularly": "ഉപകരണങ്ങൾ പതിവായി അണുവിമുക്തമാക്കുക",
    "Copper soap": "കോപ്പർ സോപ്പ് (Copper soap)",
    "Biological controls (Bacillus subtilis)": "ജൈവ നിയന്ത്രണങ്ങൾ (ബാസിലസ് സബ്റ്റിലിസ്)",
    "Remove infected leaves immediately": "രോഗം ബാധിച്ച ഇലകൾ ഉടൻ നീക്കം ചെയ്യുക",
    "Sulfur-based fungicides": "സൾഫർ അടിസ്ഥാനമാക്കിയുള്ള കുമിൾനാശിനികൾ",
    "Neem oil": "വേപ്പെണ്ണ",
    "Mancozeb": "മാൻകോസെബ് (Mancozeb)",
    "Water at roots": "വേരുകളിൽ നനയ്ക്കുക",
    "Improve air circulation": "വായു സഞ്ചാരം മെച്ചപ്പെടുത്തുക",
    "Slow recovery potential - chemicals limited": "വീണ്ടെടുക്കൽ സാവധാനത്തിലാണ് - രാസവസ്തുക്കൾ പരിമിതമാണ്",
    "Soil solarization": "മണ്ണ് സൗരോർജ്ജീകരണം (Soil solarization)",
    "Long-term crop rotation (3-4 years)": "ദീർഘകാല വിള പരിക്രമണം (3-4 വർഷം)",
    "Plant resistant varieties": "പ്രതിരോധ ശേഷിയുള്ള ഇനങ്ങൾ നടുക",
    "Control nematode populations": "നീമറ്റോഡുകളെ നിയന്ത്രിക്കുക",
    "Soil amendments with compost": "കമ്പോസ്റ്റ് ഉപയോഗിച്ച് മണ്ണ് മെച്ചപ്പെടുത്തുക",
    "Bio-fungicides (Trichoderma)": "ജൈവ കുമിൾനാശിനികൾ (Trichoderma)",
    "Potassium bicarbonate": "പൊട്ടാസ്യം ബൈകാർബണേറ്റ്",
    "Myclobutanil": "മൈക്ലോബുട്ടാനിൽ",
    "Select resistant varieties": "പ്രതിരോധ ഇനങ്ങൾ തിരഞ്ഞെടുക്കുക",
    "Avoid overhead watering": "ഇലകളിൽ വെള്ളം ഒഴിക്കുന്നത് ഒഴിവാക്കുക",
    "Remove infected plant debris": "രോഗം ബാധിച്ച അവശിഷ്ടങ്ങൾ നീക്കം ചെയ്യുക",
    "Milk spray (1:10 ratio)": "പാൽ സ്പ്രേ (1:10 അനുപാതം)",
    "Baking soda solution": "ബേക്കിംഗ് സോഡ ലായനി",
    "Azoxystrobin": "അസോക്സിസ്ട്രോബിൻ",
    "Propiconazole": "പ്രൊപ്പിക്കോണസോൾ",
    "Plant resistant hybrids": "പ്രതിരോധ ശേഷിയുള്ള സങ്കരയിനങ്ങൾ",
    "Monitor nutrient levels (avoid excess N)": "പോഷക നില നിരീക്ഷിക്കുക (അമിത നൈട്രജൻ ഒഴിവാക്കുക)",
    "Apply fungicides at early signs": "ആദ്യ ലക്ഷണങ്ങളിൽ തന്നെ കുമിൾനാശിനി പ്രയോഗിക്കുക",
    "Sulfur dust": "സൾഫർ പൊടി",
    "Remove alternate hosts/weeds": "കളകളും മറ്റ് ആതിഥേയ സസ്യങ്ങളും നീക്കം ചെയ്യുക",
    "Control insect vectors (aphids/thrips)": "കീടങ്ങളെ നിയന്ത്രിക്കുക (അഫിഡ്‌സ്/ത്രിപ്‌സ്)",
    "No direct chemical cure for virus": "വൈറസിനായി നേരിട്ടുള്ള രാസചികിത്സയില്ല",
    "Use virus-free certified seeds": "വൈറസ് വിമുക്ത സർട്ടിഫൈഡ് വിത്തുകൾ ഉപയോഗിക്കുക",
    "Control weeds": "കളകളെ നിയന്ത്രിക്കുക",
    "Remove infected plants immediately (roguing)": "രോഗം ബാധിച്ച ചെടികളെ ഉടൻ നീക്കം ചെയ്യുക",
    "Reflective mulches": "റിഫ്ലക്റ്റീവ് മൾച്ചുകൾ",
    "Milk spray to prevent mechanical transmission": "രോഗ വ്യാപനം തടയാൻ പാൽ സ്പ്രേ ചെയ്യുക",
    "Chlorothalonil": "ക്ലോറോതലോനിൽ",
    "Copper fungicides": "കോപ്പർ കുമിൾനാശിനികൾ",
    "Mulching to prevent soil splash": "മണ്ണ് തെറിക്കുന്നത് തടയാൻ പുതയിടുക",
    "Water at base of plant": "ചെടിയുടെ ചുവട്ടിൽ മാത്രം നനയ്ക്കുക",
    "Remove lower leaves": "താഴത്തെ ഇലകൾ നീക്കം ചെയ്യുക",
    "Copper spray": "കോപ്പർ സ്പ്രേ",
    "Biological fungicides": "ജൈവ കുമിൾനാശിനികൾ",
    "Enhanced air circulation": "മെച്ചപ്പെട്ട വായു സഞ്ചാരം",
    "Captan": "കാപ്റ്റാൻ",
    "Benomyl": "ബെനോമിൽ",
    "Proper drainage": "ശരിയായ ഡ്രെയിനേജ്",
    "Remove infected fruit/twigs": "രോഗം ബാധിച്ച കായ്കളും ചില്ലകളും നീക്കം ചെയ്യുക",
    "Hot water seed treatment": "ചൂടുവെള്ളത്തിൽ വിത്ത് ചികിൽസ",
    "Chlorothalonil (Daconil)": "ക്ലോറോതലോനിൽ (ഡാക്കോണിൽ)",
    "Copper-based fungicide (Bordeaux mixture)": "കോപ്പർ അധിഷ്ഠിത കുമിൾനാശിനി (ബോർഡോ മിശ്രിതം)",
    "Clean greenhouse structures": "ഹരിതഗൃഹ ഘടനകൾ വൃത്തിയാക്കുക",
    "Neem oil spray": "വേപ്പെണ്ണ സ്പ്രേ",
    "Compost tea": "കമ്പോസ്റ്റ് ചായ",
    "Ridomil Gold": "റിഡോമിൽ ഗോൾഡ്",
    "Destroy culled potatoes": "ഉപേക്ഷിച്ച ഉരുളക്കിഴങ്ങുകൾ നശിപ്പിക്കുക",
    "Plant certified seed": "സർട്ടിഫൈഡ് വിത്തുകൾ ഉപയോഗിക്കുക",
    "Monitor weather (cool/wet favors blight)": "കാലാവസ്ഥ നിരീക്ഷിക്കുക",
    "Kill vines before harvest": "വിളവെടുപ്പിന് മുമ്പ് വള്ളികൾ നശിപ്പിക്കുക",
    "Copper products": "കോപ്പർ ഉൽപ്പന്നങ്ങൾ",
    "Hydrogen dioxide": "ഹൈഡ്രജൻ ഡയോക്സൈഡ്",
    "Continue regular monitoring": "പതിവായി നിരീക്ഷിക്കുക",
    "Maintain proper irrigation": "ശരിയായ ജലസേചനം ഉറപ്പാക്കുക",
    "Apply balanced fertilizers": "സമീകൃത വളം പ്രയോഗിക്കുക",
    "Disinfect tools": "ഉപകരണങ്ങൾ അണുവിമുക്തമാക്കുക",
    "Crop rotation": "വിള പരിക്രമണം",
    "Neem oil to repel vectors": "കീടങ്ങളെ അകറ്റാൻ വേപ്പെണ്ണ",
    "Please upload a clear image of a crop leaf": "വിളയുടെ ഇലയുടെ വ്യക്തമായ ചിത്രം അപ്‌ലോഡ് ചെയ്യുക",
    "Ensure the image is well-lit": "ചിത്രത്തിന് നല്ല വെളിച്ചമുണ്ടെന്ന് ഉറപ്പാക്കുക",
    "Focus on the plant tissue": "സസ്യഭാഗങ്ങളിൽ ശ്രദ്ധ കേന്ദ്രീകരിക്കുക",
    allIndiaCommunity: "അഖിലേന്ത്യ കമ്മ്യൂണിറ്റി",
    discussNation: "രാജ്യത്തുടനീളമുള്ള കർഷകരുമായി ചർച്ച ചെയ്യുക",
    tabAllIndia: "മുഴുവൻ ഇന്ത്യ",
    tabSolutions: "പരിഹാരങ്ങൾ",
    tabMyRegion: "എന്റെ പ്രദേശം",
    genDiscussion: "പൊതു ചർച്ച",
    suggSolution: "നിർദ്ദേശം / പരിഹാരം",
    solutionBadge: "പരിഹാരം",
    suggestedSol: "നിർദ്ദേശിച്ച പരിഹാരം",
    writeComment: "കമന്റ് എഴുതുക...",
    noDiscussionsCat: "ഈ വിഭാഗത്തിൽ ചർച്ചകളില്ല.",
    justNow: "ഇപ്പോൾ"
};

// 4. Create Context
const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    // Default to English if no valid language found
    const savedLang = localStorage.getItem('language');
    const [lang, setLang] = useState(savedLang || 'en');

    // Update localStorage when language changes
    React.useEffect(() => {
        localStorage.setItem('language', lang);
    }, [lang]);

    const translations = {
        en: {
            ...en,
            allIndiaCommunity: "All India Community",
            discussNation: "Discuss ideas & solutions with farmers across the nation",
            tabAllIndia: "All India",
            tabSolutions: "Solutions",
            tabMyRegion: "My Region",
            genDiscussion: "General Discussion",
            suggSolution: "Suggestion / Solution",
            solutionBadge: "Solution",
            suggestedSol: "Suggested Solution",
            writeComment: "Write a comment...",
            noDiscussionsCat: "No discussions found in this category.",
            justNow: "Just now"
        },
        hi: {
            ...hi,
            allIndiaCommunity: "अखिल भारतीय समुदाय",
            discussNation: "देश भर के किसानों के साथ विचारों और समाधानों पर चर्चा करें",
            tabAllIndia: "पूरी भारत",
            tabSolutions: "समाधान",
            tabMyRegion: "मेरा क्षेत्र",
            genDiscussion: "सामान्य चर्चा",
            suggSolution: "सुझाव / समाधान",
            solutionBadge: "समाधान",
            suggestedSol: "सुझाया गया समाधान",
            writeComment: "एक टिप्पणी लिखें...",
            noDiscussionsCat: "इस श्रेणी में कोई चर्चा नहीं मिली।",
            justNow: "अभी"
        },
        te: {
            ...te,
            allIndiaCommunity: "అఖిల భారత సంఘం",
            discussNation: "దేశవ్యాప్తంగా ఉన్న రైతుల తో చర్చించండి",
            tabAllIndia: "మొత్తం భారతదేశం",
            tabSolutions: "పరిష్కారాలు",
            tabMyRegion: "నా ప్రాంతం",
            genDiscussion: "సాధారణ చర్చ",
            suggSolution: "సూచన / పరిష్కారం",
            solutionBadge: "పరిష్కారం",
            suggestedSol: "సూచించిన పరిష్కారం",
            writeComment: "వ్యాఖ్య రాయండి...",
            noDiscussionsCat: "ఈ వర్గంలో చర్చలు లేవు.",
            justNow: "ఇప్పుడే"
        },
        kn: {
            ...kn,
            allIndiaCommunity: "ಅಖಿಲ ಭಾರತ ಸಮುದಾಯ",
            discussNation: "ದೇಶದಾದ್ಯಂತದ ರೈತರೊಂದಿಗೆ ಚರ್ಚಿಸಿ",
            tabAllIndia: "ಇಡೀ ಭಾರತ",
            tabSolutions: "ಪರಿಹಾರಗಳು",
            tabMyRegion: "ನನ್ನ ಪ್ರದೇಶ",
            genDiscussion: "ಸಾಮಾನ್ಯ ಚರ್ಚೆ",
            suggSolution: "ಸಲಹೆ / ಪರಿಹಾರ",
            solutionBadge: "ಪರಿಹಾರ",
            suggestedSol: "ಸೂಚಿಸಿದ ಪರಿಹಾರ",
            writeComment: "ಟಿಪ್ಪಣಿ ಬರೆಯಿರಿ...",
            noDiscussionsCat: "ಈ ವರ್ಗದಲ್ಲಿ ಯಾವುದೇ ಚರ್ಚೆಗಳಿಲ್ಲ.",
            justNow: "ಈಗಷ್ಟೇ"
        },
        ta: {
            ...ta,
            allIndiaCommunity: "அனைத்து இந்திய சமூகம்",
            discussNation: "நாடு முழுவதும் உள்ள விவசாயிகளுடன் விவாதிக்கவும்",
            tabAllIndia: "அனைத்து இந்தியா",
            tabSolutions: "தீர்வுகள்",
            tabMyRegion: "என் பகுதி",
            genDiscussion: "பொது விவாதம்",
            suggSolution: "பரிந்துரை / தீர்வு",
            solutionBadge: "தீர்வு",
            suggestedSol: "பரிந்துரைக்கப்பட்ட தீர்வு",
            writeComment: "கருத்து எழுதுங்கள்...",
            noDiscussionsCat: "இந்த வகையில் விவாதங்கள் இல்லை.",
            justNow: "இப்போது தான்"
        },
        ml: {
            ...ml,
            allIndiaCommunity: "അഖിലേന്ത്യ കമ്മ്യൂണിറ്റി",
            discussNation: "രാജ്യത്തുടനീളമുള്ള കർഷകരുമായി ചർച്ച ചെയ്യുക",
            tabAllIndia: "മുഴുവൻ ഇന്ത്യ",
            tabSolutions: "പരിഹാരങ്ങൾ",
            tabMyRegion: "എന്റെ പ്രദേശം",
            genDiscussion: "പൊതു ചർച്ച",
            suggSolution: "നിർദ്ദേശം / പരിഹാരം",
            solutionBadge: "പരിഹാരം",
            suggestedSol: "നിർദ്ദേശിച്ച പരിഹാരം",
            writeComment: "കമന്റ് എഴുതുക...",
            noDiscussionsCat: "ഈ വിഭാഗത്തിൽ ചർച്ചകളില്ല.",
            justNow: "ഇപ്പോൾ"
        }
    };

    const t = (key) => {
        return translations[lang][key] || translations['en'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ lang, setLang, t, translations: translations[lang] }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
